### ISSUE TITLE
Темы для выпуска #89 (3 декабря). В гостях Евгений Антонов

### ISSUE THREAD

**Issue by hack3p** [znprod/stream-topics#10]
Накидывайте вопросы нашему гостю, в этот раз это тимлид очевидность Евгений Антонов
Ссылки на Евгения:
[ТГ канал "Тимлид Очевидность"](https://t.me/general_it_talks)
[Сайт](https://antonov-dev.ru/)
[Твиттер](https://twitter.com/_jeck)

![image](https://user-images.githubusercontent.com/3073695/100496651-a6cfe600-3166-11eb-88b5-b1c9fe67fedb.png)

**Comment by githubjeka** [comment]
Кто-то же вроде гостем собирался?

**Comment by anton-okolelov** [comment]
work/life balance

и
[письменные стендапы]
(https://t.me/general_it_talks/32)

[быть тимлидом - гемор?]
(https://t.me/general_it_talks/16)

**Comment by RinatValiullov** [comment]
1. *Наброс-вопрос*:
	Динамическая или статическая типизация?

**Comment by kpblc** [comment]
продолжая тему work/life balance

1) как поддерживать рост технических скилов, в условиях когда солидную часть рабочего дня приходиться заниматься координацией команды(конкретные практики)?
2) нужно ли вообще пытаться это делать? 
3) как при этом не расстаться с ментальным и физическим здоровьем к 30/40 годам?

**Comment by xepozz** [comment]
1. Как часто хочется уйти с позиции лида?
2. Как работать разработчиком, если ушел с позиции лида? Особенно, если команду не поменял.
  К чему я: после таких смен останется team lead vision, который будешь питчить другим людям (и новому лиду в том числе). Получается, можешь стать некой точкой раздора команды и командных процессов. Стоит ли в таком случае оставаться в текущей команде или лучше сменить её?

**Comment by lFandoriNl** [comment]
Собеседовался ли ты когда то целенаправленно в компанию сразу на позицию лида? Расскажи о вопросах и деталях собеса и взяли ли тебя?

**Comment by PakhomovAlexander** [comment]
Про консультации! 

- Как пришел к этому?
- Не мучает ли синдром самозванца? 
- Доход ощутимо повысился?
- Как это вообще работает?

**Comment by xenmayer** [comment]
Видео: https://youtu.be/Kby2hMiAEOM
