### ISSUE TITLE
Тема для потенциального выпуска с приглашенным гостем (гостями) - из backend-a в frontend

### ISSUE THREAD

**Issue by Lindar90** [znprod/stream-topics#12]
я начинал карьеру 10 лет назад, когда мы еще звались вебразработчиками и не было четкого разделения на фронт и бэк. Когда начался активный бум в фронтэнде, многие с кем я начинал ушли чисто в бэк. А я пытался поспеть и там и там и так получилось, что прошел путь от PHP dev, дальше к  Fullstack dev и закончил как Fullstack Lead,  а сейчас Frontend Lead. 

И я вот лично за все это время столкнулся с такими проблемами как:
- предвзятость работадателей к резюме, когда они видят не фронтовые позиции
- в целом токсичность frontend сообщества к тем, кто приходит с PHP
- с синдром самозванца frontend-е
- иногда действительно нехватало времени успевать глубоко развеваться в 2 ветки, а надо было брать и делать горячие задачи
- сомненями можно ли вообще быть хорошим Fullstack разработчиком сегодня
- и прочее

В общем очень интересно было бы послушать похожие истории,  как люди спровлялись с подобными проблемами.

**Comment by xenmayer** [comment]
По большей части вопросов у нас есть опыт. Так что если будет невтерпеж, то тащи в рядовой эфир. Если будет пожелание по обсуждению вопроса к какому-то конкретному гостю, то welcome!

**Comment by Lindar90** [comment]
@xenmayer ок, закинул в основной выпуск
