### ISSUE TITLE
Темы для выпуска #094

### ISSUE THREAD

**Issue by anton-okolelov** [znprod/stream-topics#16]
Предлагайте темы для следущего эфира!

**Comment by DevNulPavel** [comment]
https://habr.com/ru/news/t/535914/

Не, ну такое точно нельзя не обсудить) Картинка в начале просто прекрасна)

**Comment by zetroot** [comment]
> https://habr.com/ru/news/t/535914/
> Не, ну такое точно нельзя не обсудить) Картинка в начале просто прекрасна) Отличный опенсорс проект, чтобы поучаствовать и сделать мир лучше)

Позволю себе процитировать комментарий из поста, ибо он прекрасен: "В жопу этот ваш руст!"

**Comment by RinatValiullov** [comment]
Всё равно его не брошу, потому что он хороший!

- [PHP “dying” this Decade: One Year After](https://medium.com/swlh/one-year-from-php-dying-this-decade-32e2b7a79507)
- [Using PHP for Good — How It’s Not Great, and Why It Could Work for You](https://medium.com/swlh/using-php-for-good-why-it-sucks-and-how-to-make-it-amazing-for-yourself-1158d5e00e4c)

`+`

Потанцуем?

[Why the Dancing Robots Are a Really, Really Big Problem](https://medium.com/swlh/why-the-dancing-robots-are-a-really-really-big-problem-4faa22c7f899)

**Comment by xenmayer** [comment]
[9 Early Signs You Will Be a Successful Programmer](https://levelup.gitconnected.com/9-early-signs-you-will-be-a-successful-programmer-1a604f04be39)

**Comment by xenmayer** [comment]
[Названы победители 27 конкурса по написанию запутанного кода на языке Си](https://www.opennet.ru/opennews/art.shtml?num=54350)

**Comment by xenmayer** [comment]
[Белоруссия запустила платную национальную электронную почту](https://www.rbc.ru/technology_and_media/05/01/2021/5ff38daf9a79472b27f5e707#:~:text=%D0%91%D0%B5%D0%BB%D0%BE%D1%80%D1%83%D1%81%D1%81%D0%B8%D1%8F%20%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D1%82%D0%B8%D0%BB%D0%B0%20%D0%BF%D0%BB%D0%B0%D1%82%D0%BD%D1%83%D1%8E%20%D0%BD%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D1%83%D1%8E%20%D1%8D%D0%BB%D0%B5%D0%BA%D1%82%D1%80%D0%BE%D0%BD%D0%BD%D1%83%D1%8E%20%D0%BF%D0%BE%D1%87%D1%82%D1%83,-%D0%A7%D1%82%D0%BE%D0%B1%D1%8B%20%D0%BE%D1%82%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D1%82%D1%8C%20%D0%BE%D0%B1%D1%8B%D1%87%D0%BD%D0%BE%D0%B5&text=%D0%9F%D1%80%D0%B8%20%D1%8D%D1%82%D0%BE%D0%BC%20%D1%83%D1%81%D0%BB%D1%83%D0%B3%D0%B0%20%D1%8F%D0%B2%D0%BB%D1%8F%D0%B5%D1%82%D1%81%D1%8F%20%D0%BF%D0%BB%D0%B0%D1%82%D0%BD%D0%BE%D0%B9,%D0%B3%D0%B0%D1%80%D0%B0%D0%BD%D1%82%D0%B8%D1%80%D1%83%D0%B5%D1%82%20%D0%B1%D0%B5%D0%B7%D0%BE%D0%BF%D0%B0%D1%81%D0%BD%D0%BE%D1%81%D1%82%D1%8C%20%D0%B8%20%D0%BA%D0%BE%D0%BD%D1%84%D0%B8%D0%B4%D0%B5%D0%BD%D1%86%D0%B8%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D1%81%D1%82%D1%8C%20%D0%BF%D0%B5%D1%80%D0%B5%D0%BF%D0%B8%D1%81%D0%BA%D0%B8.)

**Comment by xenmayer** [comment]
[Тулза для генерации голоса мультяшных персонажей](https://15.ai/)

**Comment by anton-okolelov** [comment]
[На реддите обсуждают размер строки 80 символов для кода](https://www.reddit.com/r/programming/comments/kpq460/linus_torvalds_rails_against_80characterlines_as/)

**Comment by battlmonstr** [comment]
чувак шел к успеху (и пришел)
https://habr.com/ru/company/vdsina/blog/536112/

**Comment by anton-okolelov** [comment]
[Джетбеейнс подозревают в хакерских атаках](https://www.nytimes.com/2021/01/06/us/politics/russia-cyber-hack.html#click=https://t.co/rpEG4N7VK6)

**Comment by anton-okolelov** [comment]
[Закон про обязательный софт опубликован](http://publication.pravo.gov.ru/Document/View/0001202101060012)

**Comment by NChechulin** [comment]
https://m.habr.com/ru/news/t/536348/

Исходные коды компании Nissan утекли

**Comment by xenmayer** [comment]
Видео: https://youtu.be/6S_njGyDIpM
