### ISSUE TITLE
Темы для выпуска #095 (14 января)

### ISSUE THREAD

**Issue by xenmayer** [znprod/stream-topics#17]
Привет! Ждем Ваши вопросы и темы к эфиру 🎙.

**Comment by UzixLS** [comment]
Про травлю Parler: https://3dnews.ru/1029656/amazon-otkazala-parler-v-uslugah-hostinga-otklyuchenie-11-yanvarya-v-1059-msk

**Comment by RinatValiullov** [comment]
[В восьмицилиндровом новенький (пока экспериментальный есессна) _non-backtracking RegExp движок_](https://v8.dev/blog/non-backtracking-regexp) (* и здесь [rust](https://github.com/rust-lang/regex) засветился)

**Comment by xenmayer** [comment]
[Софтовый датчик присутствия на Linux AP + ESP8266](https://habr.com/ru/post/536992/)

**Comment by anton-okolelov** [comment]
[Отчет "State of js 2020", да еще и на русском есть](https://2020.stateofjs.com/ru-RU/)

**Comment by anton-okolelov** [comment]
[просто пиздец что творится на РЖД](https://habr.com/ru/post/536750/)

**Comment by xenmayer** [comment]
[У программиста из США остались две попытки для открытия самоуничтожающейся флешки. Там ключ к биткойнам на $237 млн](https://habr.com/ru/news/t/537044/)

**Comment by anton-okolelov** [comment]
https://thebell.io/buntovshhiki-ne-projdut-kak-trampa-i-ego-storonnikov-otrezayut-ot-politicheskogo-finansirovaniya

**Comment by RinatValiullov** [comment]
> [thebell.io/buntovshhiki-ne-projdut-kak-trampa-i-ego-storonnikov-otrezayut-ot-politicheskogo-finansirovaniya](https://thebell.io/buntovshhiki-ne-projdut-kak-trampa-i-ego-storonnikov-otrezayut-ot-politicheskogo-finansirovaniya)

`+`

https://twitter.com/jack/status/1349510769268850690

**Comment by xenmayer** [comment]
Видео: https://youtu.be/rH-daNCq-Ss
