### ISSUE TITLE
Темы для выпуска #096 (21 января). В гостях Алексей Фёдоров

### ISSUE THREAD

**Issue by xenmayer** [znprod/stream-topics#18]
Накидывайте вопросы нашему гостю, в этот раз это **Алексей Фёдоров**, продюсер и сооснователь **JUG Ru Group**.

![image](https://user-images.githubusercontent.com/3073695/104334355-496bda80-5503-11eb-9be5-c30d73e3ce70.png)

**Ссылки на Алексея:**

Твиттерок: https://twitter.com/23derevo
Телега: https://t.me/channel_23derevo
Некоторые видео
[Обедающие Философы наносят ответный удар!](https://youtu.be/qrQ21myRSRc)
[Синхронизация без блокировок и СМС](https://youtu.be/GPpNpgKtOrA)
[Вторая чашка кофе с Joker](https://youtu.be/6bMSz8HGBQE)
[Ретроспектива JUG.ru: с 2012 по наши дни](https://youtu.be/FPJCV6A458c)
[Ангелы и демоны многопоточного программирования](https://youtu.be/MUigCMNSXcI)
[Интервьюируем работодателя](https://youtu.be/h4NICbw8oq8)
[Бренд и его место в маркетинге](https://youtu.be/O3lZk7uBWHk)
[Отдел по продаже счастья](https://youtu.be/sijRHke7Xsw)
[Модель SOSTAC в применении к HR-бренду](https://youtu.be/ukW1uw4lgzk)
Подкасты
[Лабибэй](https://music.yandex.ru/album/10938133/track/74004993)

**Comment by anton-okolelov** [comment]
Кем ты хотел стать в детстве?
Почему променял джаву на организаторство?
Для чего нужно 2-3 дерево?

**Comment by RinatValiullov** [comment]
Зачем лягушка в формалине?

**Comment by xenmayer** [comment]
@RinatValiullov в чатике поднимал вопрос про конфликт с курсами https://youtu.be/p3vfmNIjmW4
tl;dr;
Крутой чувак решил поревьювать курс по Vue.js. Его возмутило, что курс - пересказ официальной документации практически без отхождения в сторону. Он написал в службу поддержки с просьбой вернуть деньги и протоколировал происходящие далее события.
![image](https://user-images.githubusercontent.com/3073695/104949575-3b6cfc80-59d0-11eb-8058-6bd309b3ae5f.png)

Многих возмутила стоимость курса. Как ты относишься к ценообразованию на курсы? 

Должен ли преподаватель быть практиком?

**Comment by xenmayer** [comment]
Было ли когда-нибудь желание бросить айтишечку и открыть свой свечной заводик?

**Comment by xenmayer** [comment]
Насколько жизнеспособная идея: добавить нетворкинг конференций в игры? Например добавить функционал конференции в Cyberpunk 2077 или Ведьмака?

**Comment by xenmayer** [comment]
Насколько сложная система бэкапов видео на Джугах?
Терялись ли когда-нибудь записи?
Терялись ли когда-нибудь докладчики?

**Comment by anton-okolelov** [comment]
Нафига тебе три внешних монитора 4K

**Comment by Ligalaiz** [comment]
Ваше мнение о законе по запрету просветительской деятельности?
https://www.youtube.com/watch?v=dgOscO6HA2o

**Comment by xenmayer** [comment]
Когда начал прогать?
В каком возрасте надо начинать учить программировать?
Как лучше обучать - через бизнесовые задачи или математико-логико-олимпиадные?

**Comment by xenmayer** [comment]
Видео: https://youtu.be/l47UnfVnVlY
