### ISSUE TITLE
Темы для выпуска #097 (28 января)

### ISSUE THREAD

**Issue by xenmayer** [znprod/stream-topics#19]
Привет! Ждем Ваши вопросы и темы к эфиру 🎙.

**Comment by antonov-e-v** [comment]
покомментируйте посты:
https://t.me/full_of_hatred/426  "Манямечты о карьере инженера"
https://habr.com/ru/post/537786/ "Олды в ИТ"

**Comment by Zanziver** [comment]
Brave стал первым браузером, который внедрил поддержку пирингового сетевого протокола IPFS.
[https://habr.com/ru/news/t/538196/](https://habr.com/ru/news/t/538196/)

**Comment by xepozz** [comment]
https://tproger.ru/news/glava-github-nazval-zakonnyj-metod-ne-uvedomljat-polzovatelej-ob-ispolzovanii-cookie/

**Comment by xenmayer** [comment]
[Эксперт обнаружил, что на сайт законодательства России можно зайти под admin/admin. Сейчас это исправлено](https://habr.com/ru/news/t/538618/)

**Comment by xenmayer** [comment]
[Сбер купил робота-пса Spot от Boston Dynamics](https://habr.com/ru/news/t/538582/)

**Comment by xenmayer** [comment]
[«Ъ»: Производители смартфонов не могут договориться с российскими разработчиками о предустановке приложений](https://habr.com/ru/news/t/538502/)

**Comment by zetroot** [comment]
"Взлом" продуктовых магазинов
https://habr.com/ru/post/538602/
https://habr.com/ru/post/427905/

**Comment by zetroot** [comment]
> 
> 
> [Сбер купил робота-пса Spot от Boston Dynamics](https://habr.com/ru/news/t/538582/)

У них патронов явно больше! Но вот подкаста такого нет

**Comment by anton-okolelov** [comment]
[Intel  возвращает старого CTO с пенсии ](https://habr.com/ru/company/dcmiran/blog/538694/)

**Comment by RinatValiullov** [comment]
В интернете в который раз кто-то неправ

[Что делать если вам добровольно-принудительно меняют трудовой договор, и причем тут импортозамещение](https://habr.com/ru/post/538686)

**Comment by anton-okolelov** [comment]
go 1.16 выйдет через пару лней

**Comment by xenmayer** [comment]
[Налоговая служба ЮАР разработала собственный браузер, чтобы не отказываться от Flash Player](https://habr.com/ru/news/t/539676/)

**Comment by xenmayer** [comment]
[Reddit против Уолл-Стрит: флешмоб вокруг акций GameStop стал интернет-феноменом с мемами, обсуждениями и последствиями](https://tjournal.ru/internet/330869-reddit-protiv-uoll-strit-fleshmob-vokrug-akciy-gamestop-stal-internet-fenomenom-s-memami-obsuzhdeniyami-i-posledstviyami)

**Comment by xenmayer** [comment]
Видео: https://youtu.be/9a0K38h-OMo
