### ISSUE TITLE
Темы для выпуска. Цинковый прод #083

### ISSUE THREAD

**Issue by anton-okolelov** [znprod/stream-topics#2]
Пишите темы, кидайте ссылки, вопросы - всё, что хотели бы обсудить в следующем выпуске!

**Comment by xenmayer** [comment]
[AWS forked my project and launched it as its own service](https://twitter.com/tim_nolet/status/1317061818574082050)

**Comment by RinatValiullov** [comment]
[Which Programming Languages Use the Least Electricity?](https://thenewstack.io/which-programming-languages-use-the-least-electricity)

**Comment by xenmayer** [comment]
[Пассажиров Москвы пытаются отследить по MAC-адресам](https://habr.com/ru/news/t/524224/)

**Comment by xenmayer** [comment]
[Chrome exempts Google sites from user site data settings](https://lapcatsoftware.com/articles/chrome-google.html)

**Comment by xenmayer** [comment]
[Sort every collection you output](https://hilton.org.uk/blog/sort-every-collection)

**Comment by xenmayer** [comment]
[Выпуск децентрализованного коммуникационного клиента Jami](https://www.opennet.ru/opennews/art.shtml?num=53920)

**Comment by xenmayer** [comment]
[Уязвимость во FreeType, эксплуатируемая через TTF-шрифт и затрагивающая браузеры](https://www.opennet.ru/opennews/art.shtml?num=53922)

**Comment by xenmayer** [comment]
[В Telegram обнаружили сеть платных ботов DeepNude](https://habr.com/ru/news/t/524530/)

**Comment by zetroot** [comment]
Про обработку исключений поговорите, нормальная тема хоть и от "короля"
[Я принес вам решение проблемы с исключениями в C#. Но вам не понравится ](https://habr.com/ru/company/vdsina/blog/523618/)
