### ISSUE TITLE
Темы для выпуска #098 (4 февраля). Elixir заменит PHP

### ISSUE THREAD

**Issue by xenmayer** [znprod/stream-topics#20]
Наши друзья из SkyEng предложили обсудить Elixir глазами PHP-шника.
К нам придет Валентин Назаров и расскажет о своих впечатлениях.

Кидайте свои вопросы или предложения к обсуждению.

**Comment by RinatValiullov** [comment]
Ну и по традиции хотелось бы узнать что такое монада )

**Comment by Ferikl** [comment]
Пробовал я врываться в Элексир и Феникс, после ларавель, это как шаг назад (лет на 5 отстают). Еще при этом ознакомлении осознал что веб это про строки, а в элексире все сложно с этим. Ну и не сильно представляю как бизнес логику писать серьезную еще и динамические типы... сейчас все хотят построже чтоб было. Как на практике в вебе использовать систему акторов? графКЛ чтоли? так может нода тогда..., Все имхо, го обсуждать.

**Comment by anton-okolelov** [comment]
видео

https://www.youtube.com/watch?v=u16Jbs3_QY4
