### ISSUE TITLE
Темы для выпуска #099 (11 февраля). Айтишники и здоровое питание. В гостях диетолог Антоний Мальков

### ISSUE THREAD

**Issue by anton-okolelov** [znprod/stream-topics#21]
Сидишь скрюченный, не отрывая жопы, и ешь печеньки? Заработал лишние килограммы и изжогу? Или наоборот, дофига спортсмен, и хочешь более эффективно питаться? 

Приходи на эфир 11 февраля в 20:00 по Москве и задай Антонию вопрос!

Лучше вопросы набросить прямо здесь в комментах заранее!

**Comment by anton-okolelov** [comment]
Как правильно худеть? Реально ли это, считать калории всю жизнь?

**Comment by anton-okolelov** [comment]
Вредно ли интервальное голодание?

**Comment by anton-okolelov** [comment]
что важнее для похудения - правильное питание или занятия спортом?

**Comment by lFandoriNl** [comment]
Что делать если кушать хочеца, худеть хочеца, ничего не делать хочеца. Как быть и как жить?

**Comment by vlamai** [comment]
Каких врачей обойти, какие анализы сдать что бы понять насколько все плохо ? с "диетологической" точки зрения

**Comment by kattaris** [comment]
Больше года сплю с 21:00 до 05:00, ем с интервалом 12 часов, физ нагрузка каждый будний день минимум 30 минут (турник, брусья, скамья для пресса, гантели) днем. Рост 190, вес 91. По врачам не хожу, нет нужды. Чувствую себя шикарно, по сравнению с тем что было раньше, но вопрос - не слишком ли высокая нагрузка на организм, в плане таких интервалов и нагрузки? Не начнет ли что-то незаметно сбоить через какое-то время?

**Comment by battlmonstr** [comment]
1. что вреднее, жир или сахар?
2. реально ли программисту отказаться от сахара, не потеряв мыслетопливо?

**Comment by avbabushkin** [comment]
Бывает так что приходиться работать ночью. Какие продукты можно жрать ночью? :)

**Comment by vlamai** [comment]
На сколько полезно есть каши, мюсли? Надо ли оно вообще?

**Comment by php-coder** [comment]
> На сколько полезно есть каши, мюсли? Надо ли оно вообще?

... и супы еще

**Comment by anton-okolelov** [comment]
Насколько вредны энергетики?

**Comment by anton-okolelov** [comment]
видос https://www.youtube.com/watch?v=9pyZcKv1hsg
