### ISSUE TITLE
Юбилейный выпуск #100!!!1111одинодинодин

### ISSUE THREAD

**Issue by anton-okolelov** [znprod/stream-topics#22]
Накидывайте весёлые темы ))

**Comment by anton-okolelov** [comment]
Нужно ли программисту хобби, перпендикулярное основной работе?

https://habr.com/ru/post/542550/

**Comment by anton-okolelov** [comment]
Как нанимать тимлида
https://etolstoy.com/teamlead-interview/

**Comment by xenmayer** [comment]
Сколько лет Мертвому Комару?

**Comment by RinatValiullov** [comment]
Пять фраз, которые никогда не стоит говорить своему тимлиду?

**Comment by xenmayer** [comment]
[Enums vote closes today: 44 yes an 7 no; enums are coming in PHP 8.1!](https://www.reddit.com/r/PHP/comments/lln22x/enums_vote_closes_today_44_yes_an_7_no_enums_are/)

**Comment by xenmayer** [comment]
[Работу на haskell все таки можно найти)](https://habr.com/ru/company/typeable/blog/542440/)

**Comment by xenmayer** [comment]
[Северо-Корейская тема для Ubuntu, Kubuntu](https://github.com/BlackOtton/RedStar-Media)

**Comment by ovr** [comment]
- [Релиз ядра Linux 5.11](https://www.opennet.ru/opennews/art.shtml?num=54581) - тут интерестно, что Itanium все

**Comment by artjomka** [comment]
Возникает такое ощущение, что пхпешники переходят в гошников - правда ли это и почему если так ?

**Comment by Pulverok** [comment]
GoLang в реальных боевых задачах, все за и против, где лучше использовать в хайлоаде, общие ощущения от языка

**Comment by kpblc** [comment]
ну раз выпуск юбилейный, то и вопросы пусть будут тематические

делаем скачек во времени на 100 выпусков НАЗАД, попадаем в 11 мая 2019 г. находим там "самого себя из прошлого":

1) помимо совета соскочить с php и уйти в rast, какой бы еще совет вы ему дали?
2) на какой его вопрос отказались бы отвечать или ответили бы нагло соврав?

отдышались, после скачка в прошлое, скакнули в настоящее, а потом сходу делаем еще один скачек во времени, но уже на 100 выпусков ВПЕРЕД, попадаем в NaN undefined NaN г. находим там "самого себя из будущего":

1) помимо вопроса "почему Антон не прикрутил донаты", какой бы вопрос, вы бы задали "самому себе из будущего" про подкаст, да про жизнь айтишную? или может не про айтишную жизнь?
2) если бы этот "дед из будущего" попытался вас поучить жизни и дать несколько бестолковых бесячих советов, то в ответ на какой именно из его советов, вы бы провели ему болевой прием + бросок через бедро, с последующим быстрым  побегом обратно в свое время?

**Comment by xenmayer** [comment]
Видео-версия: https://youtu.be/FvmjRbM1GmI
Аудио-версия(будет доступна 20.02 в 6:00 по МСК): https://soundcloud.com/znprod/vypusk-100-yubileynyy/s-fJOh4f0r3jC
