### ISSUE TITLE
Темы для выпуска #101 (25 февраля)

### ISSUE THREAD

**Issue by xenmayer** [znprod/stream-topics#23]
Привет! Ждем Ваши вопросы и темы к эфиру 🎙.

**Comment by xenmayer** [comment]
[Экономим ресурсы и успеваем в срок: зачем подключать QA-инженера в начале работы над фичей](https://habr.com/ru/post/543318/)

**Comment by xenmayer** [comment]
[В Китае все чаще меняют менеджеров на алгоритмы: те следят за работниками, дают им задачи и могут списать часть зарплаты](https://vc.ru/hr/209527-v-kitae-vse-chashche-menyayut-menedzherov-na-algoritmy-te-sledyat-za-rabotnikami-dayut-im-zadachi-i-mogut-spisat-chast-zarplaty)

**Comment by xenmayer** [comment]
[Туннельный синдром, близорукость, выгорание: чем болеют айтишники](https://tproger.ru/articles/tunnelnyj-sindrom-blizorukost-vygoranie-chem-bolejut-ajtishniki/)

**Comment by xenmayer** [comment]
[Доля WordPress перевалила за 40% среди топ 10 млн сайтов в рейтинге Alexa](https://oddstyle.ru/wordpress-2/novosti-wordpress/dolya-wordpress-perevalila-za-40-sredi-top-10-mln-sajtov-v-rejtinge-alexa.html)

**Comment by NChechulin** [comment]
[Атака на зависимости позволила выполнить код на серверах PayPal, Micrоsoft, Apple, Netflix, Uber и ещё 30 компаний](https://www.opennet.ru/opennews/art.shtml?num=54566)

**Comment by lFandoriNl** [comment]
Там один котохлеб высказал свое не нужное мнения в массах на тему что новичком быть сложно, и представляете! Она назвал циклы чертовски сложными вещами. А что вы думаете об этой глупости?
https://twitter.com/maxim_koylo/status/1364643508825563139

**Comment by NChechulin** [comment]
> Там один котохлеб высказал свое не нужное мнения в массах на тему что новичком быть сложно, и представляете! Она назвал циклы чертовски сложными вещами. А что вы думаете об этой глупости?

А мы люди простые, учим в унике плюсы после питона. Проблема налицо: для многих сахар и простота питона были данностью, а тут навалились плюсы с какими-то итераторами, статической типизацией и вот этим всем. Люди тупят, не понимают, что происходит.
А если бы учили питон после плюсов, то все бы встало на свои места: вот тут мы можем написать попроще, при этом понимая, как оно работает под капотом, там сахарочек добавили, и так далее.
И получится по итогу не черная плюсовая магия, а старая добрая инкапсуляция

**Comment by lFandoriNl** [comment]
Выдержит ли Антон хук справа?

**Comment by RinatValiullov** [comment]
> Выдержит ли Антон хук справа?

... от Никиты )

**Comment by lFandoriNl** [comment]
> > Выдержит ли Антон хук справа?
> 
> ... от Никиты )

Остановит ли их рефери Олег

**Comment by RinatValiullov** [comment]
А у вас, парни, есть битки?

[Число пользователей биткоинов во всем мире превысило 100 млн](https://habr.com/ru/news/t/544222/)

**Comment by anton-okolelov** [comment]
[Переписывание всего проекта](https://m.habr.com/ru/post/543706/)

**Comment by xenmayer** [comment]
Видео: https://www.youtube.com/watch?v=K1PFV4NwX6o

**Comment by xenmayer** [comment]
Аудио (будет доступно 27.02 в 6:00): https://soundcloud.com/znprod/101-perepisyvanie-proektov-kogda-zvat-qa-wordpress-sila/s-Oc0ruyX6DO2
