### ISSUE TITLE
Темы для выпуска #102 (4 марта)

### ISSUE THREAD

**Issue by anton-okolelov** [znprod/stream-topics#24]
Не стесняемся, накидываем темы. Вопросы, предложения тоже можно

**Comment by van-mronov** [comment]
веселые законы индустрии
https://www.netmeister.org/blog/software-engineering-laws.html

**Comment by RinatValiullov** [comment]
Ждём от Антона официального объявления, что футболки и деньги уже отправлены их счастливым обладателям. А заодно и новости о новых челленджах.

**Comment by lFandoriNl** [comment]
https://twitter.com/webholt/status/1367056502058590211

**Comment by anton-okolelov** [comment]
db для ddd

**Comment by kattaris** [comment]
Что Олег скажет про защиту кук  в новой версии фаерфокса?

**Comment by anton-okolelov** [comment]
[Flutter2](https://developers.googleblog.com/2021/03/announcing-flutter-2.html?m=1)

**Comment by lFandoriNl** [comment]
> [Flutter2](https://developers.googleblog.com/2021/03/announcing-flutter-2.html?m=1)

Уже вижу как будете обсуждать: "О флаттер 2, круто!... Так что там у нас дальше по темам?"

**Comment by RinatValiullov** [comment]
> Что Олег скажет про защиту кук в новой версии фаерфокса?

Олег не уиноуник. Совсем не уиноуник!

**Comment by dmitryplyaskin** [comment]
Релиз новой версии jquery http://blog.jquery.com/2021/03/02/jquery-3-6-0-released/

**Comment by Gosha-say** [comment]
[Минцифры предложило разрешить торговлю обезличенными персональными данными россиян](https://habr.com/ru/news/t/545402/)

<hr>

[Dice и Hired опубликовали ежегодную статистику самых высоких зарплат программистов в США](https://habr.com/ru/news/t/545502/)

**Comment by xenmayer** [comment]
Видео-версия: https://youtu.be/EAciFQyQ7js
Аудио-версия (будет доступна с 6:00 06.03.21): https://soundcloud.com/znprod/102-db-dlya-ddd-novaya-versiya-jquery

Телега: https://t.me/ZnProd
Twitter: https://twitter.com/podcast_znprod
Патреон: https://www.patreon.com/ZnProd
Сайт: https://znprod.io/
