### ISSUE TITLE
Темы для выпуска #103 (11 марта)

### ISSUE THREAD

**Issue by xenmayer** [znprod/stream-topics#25]
Привет! Ждем Ваши вопросы и темы к эфиру 🎙.

**Comment by RinatValiullov** [comment]
☁️ 
[Deno incident](https://deno.land/posts/02-03-2021-outage-post-mortem)

**Comment by kovuu** [comment]
Как вы считаете - как часто нужно менять место работы/проекты, чтобы прогрессировать и не впадать в стагнацию навыков/зарплаты?

**Comment by anton-okolelov** [comment]
Postgres: Рекурсивные CTE развиваются https://www.depesz.com/2021/02/04/waiting-for-postgresql-14-search-and-cycle-clauses/

**Comment by xenmayer** [comment]
[Минцифры и Минпросвещения предлагают запретить использование иностранного ПО в школах](https://habr.com/ru/news/t/546262/)

**Comment by xenmayer** [comment]
[РКН замедляет Twitter](https://habr.com/ru/news/t/546280/)

[Упали сайты российских госорганов](https://habr.com/ru/news/t/546312/)

**Comment by xenmayer** [comment]
[Red Hat и Google представили Sigstore, сервис для криптографической верификации кода](https://www.opennet.ru/opennews/art.shtml?num=54731)

**Comment by ovr** [comment]
- Swap problem in Kernel 5.12 [source1](https://www.phoronix.com/scan.php?page=news_item&px=Linux-5.12-Swapfile-Corrupt) (source2)(https://arstechnica.com/gadgets/2021/03/psa-linux-folks-stay-away-from-the-5-12-rc1-kernel/)

**Comment by hack3p** [comment]
Антон давно работает по Trunk based, надо чтобы поведал чёкаво, полезная/удобная штука или нет?

**Comment by xenmayer** [comment]
Видео-версия: https://youtu.be/iQiCA7SUi2Y
Аудио-версия (будет доступна с 6:00 13.03.21): https://soundcloud.com/znprod/103-rekursivnye-cte-vygoranie-zamedlenie-tvittera
