### ISSUE TITLE
 Темы для выпуска #104 (18 марта) 

### ISSUE THREAD

**Issue by hack3p** [znprod/stream-topics#26]
Привет! Ждем Ваши вопросы и темы к эфиру 🎙.

**Comment by RinatValiullov** [comment]
[GitLab прекращает использование имени "master" по умолчанию](https://www.opennet.ru/opennews/art.shtml?num=54743)

**Comment by paulmixxx** [comment]
Что думаете? 
[Три года назад нужно было изучать Docker, два года назад — Kubernetes. Сейчас — Serverless](https://habr.com/ru/company/rebrainme/blog/546324/)

**Comment by Gosha-say** [comment]
Бюрократизм и консерватизм у вашего работодателя. (Могу в эфире выступить прокурором)

**Comment by paulmixxx** [comment]
[Квантовый Компьютер. Как устроен? Как программировать? Уже?](https://vas3k.ru/blog/quantum_computing/)

**Comment by xenmayer** [comment]
[Беспилотное роботакси AutoX начинает работать в публичном режиме в Шэньчжэне (без водителей для подстраховки)](https://habr.com/ru/company/itelma/blog/547606/)

**Comment by xenmayer** [comment]
[Nvidia назвала выпуск версии драйвера RTX 3060 без ограничения майнинга случайной ошибкой](https://habr.com/ru/news/t/547608/)

**Comment by xenmayer** [comment]
[Нетология совместно с ВШЭ и РАНХиГС запускает магистерские онлайн-программы](https://habr.com/ru/company/netologyru/news/t/547594/)

**Comment by xenmayer** [comment]
[Pinduoduo стал крупнейшим маркетплейсом Китая, его основателя вынудили покинуть компанию](https://habr.com/ru/news/t/547580/)

**Comment by xenmayer** [comment]
[Я купил 300 казахских доменных имён с эмодзи и создал свой почтовый сервис](https://habr.com/ru/company/productivity_inside/blog/547456/)

**Comment by Lindar90** [comment]
Презентация Larvael Octane:
https://www.reddit.com/r/laravel/comments/m778x5/laravel_octane/
https://twitter.com/taylorotwell/status/1372397586569691139
https://twitter.com/LaraconOnline/status/1372250802882977792

**Comment by Lindar90** [comment]
Антон все время рассказывает, что у него команда самостоятельная и автономная. 
Настало время раскрыть секреты мастера, как он этого добился.
В особенности интересно, как прокачивать людей, которые технически вроде неплохие, но у них нету что ли технического виденья - они решают задачу в лоб, не думают наперед, пропускают какие-то "edge cases" и тд

**Comment by xenmayer** [comment]
Видео-версия: https://youtu.be/KQczBu6tT7Y
Аудио-версия (будет доступна с 6:00 20.03.21): https://soundcloud.com/znprod/104-byurokraty-v-it-khoroshiy-kvant-master-snova-vsyo/s-icLj6j352DM
