### ISSUE TITLE
Темы для выпуска #105 (25 марта)

### ISSUE THREAD

**Issue by xenmayer** [znprod/stream-topics#27]
Привет! Ждем Ваши вопросы и темы к эфиру 🎙.

**Comment by RinatValiullov** [comment]
[What’s up with these new not-open source licenses?](https://github.blog/2021-03-18-whats-up-with-these-new-not-open-source-licenses)

**Comment by xenmayer** [comment]
[Житель Германии перевел $560 тысяч криптомошенникам, которые представились Маском](https://habr.com/ru/news/t/548274/)

**Comment by xenmayer** [comment]
[Столичные банки начали нанимать IT-специалистов из регионов, чтобы сбить зарплаты](https://habr.com/ru/news/t/548298/)

**Comment by lFandoriNl** [comment]
Новый рокстар мира фронтенда написал статейку, а вам как бекендерам все панятна? 
А Никитке советую подумать о смене стейт менедежра, а то пока что то что я вижу с эффектором выглядит все вкусно
https://github.com/lFandoriNl/posts/blob/master/effector/lockable-event-usage.md

**Comment by xenmayer** [comment]
[Microsoft показала новые иконки папок в Windows 10](https://habr.com/ru/news/t/548860/)

**Comment by xenmayer** [comment]
[Электромобили Tesla в США можно купить за биткоины. Маск обещает не переводить в доллары криптовалюту](https://habr.com/ru/news/t/548708/)

**Comment by xenmayer** [comment]
[Роскомнадзор хочет запрашивать у новых пользователей соцсетей и мессенджеров номер паспорта, адрес, телефон и почту](https://habr.com/ru/news/t/548842/)

**Comment by xenmayer** [comment]
[Виртуальные кроссовки Gucci можно купить за 849 рублей](https://habr.com/ru/company/regionsoft/news/t/548568/)

**Comment by xenmayer** [comment]
[В даркнете растет число объявлений о поиске работы](https://habr.com/ru/news/t/548522/)

**Comment by anton-okolelov** [comment]
https://clue.engineering/2021/fibers-in-php

**Comment by xenmayer** [comment]
Видео-версия: https://youtu.be/p2pPiFZAOv8
Аудио-версия: https://soundcloud.com/znprod/105-2-goda-yagodka-opyat-tekhnicheskii-progress/s-hWuTy8gKFwb
