### ISSUE TITLE
Темы для выпуска #107 (8 апреля)

### ISSUE THREAD

**Issue by NChechulin** [znprod/stream-topics#29]

**Comment by NChechulin** [comment]
Какой-то умник наоткрывал кучу PR, в которых добавлял майнеры Monero в GitHub Actions

Пример его пулл-реквеста:
https://github.com/asc-community/AngouriMath/pull/361

**Comment by xenmayer** [comment]
Кто-нибудь заходит в Песочницу хабра иногда?
Там встречаются прикольные статьи от [Путь веб-разработчика](https://habr.com/ru/sandbox/152266/)
до [Поднятия кассандры на трех нодах)](https://habr.com/ru/sandbox/150658/)

**Comment by xenmayer** [comment]
[Oracle против Google: Верховный суд принял сторону Google в споре об авторских правах](https://habr.com/ru/company/pixonic/news/t/550886/)

**Comment by xenmayer** [comment]
Немножко контекста по теме от @NChechulin [Атака на GitHub Actions для майнинга криптовалюты на серверах GitHub](https://www.opennet.ru/opennews/art.shtml?num=54904)

**Comment by artur-tamazian** [comment]
Про NFT уже говорили? https://en.wikipedia.org/wiki/Non-fungible_token, https://decrypt.co/62898/the-10-most-expensive-nfts-ever-sold

**Comment by RinatValiullov** [comment]
Да кто такие эти ваши деврелы? И так ли они нужны на самом деле?

**Comment by xenmayer** [comment]
Мотивация от незрячего программиста
[3 года программирования вслепую. Часть 1](https://habr.com/ru/post/522146/)
[3 года программирования вслепую. Часть 2](https://habr.com/ru/post/550616/)

**Comment by RinatValiullov** [comment]
> Мотивация от незрячего программиста
> [3 года программирования вслепую. Часть 1](https://habr.com/ru/post/522146/)
> [3 года программирования вслепую. Часть 2](https://habr.com/ru/post/550616/)

Добавлю старенький, но довольно популярный перевод статьи.
[Разработка на скорости 450 слов в минуту](https://habr.com/ru/post/336600)

**Comment by xenmayer** [comment]
[Мошенники в Китае с помощью дипфейков обманули госсистему распознавания лиц на $76,2 млн](https://vc.ru/legal/228953-moshenniki-v-kitae-s-pomoshchyu-dipfeykov-obmanuli-gossistemu-raspoznavaniya-lic-na-76-2-mln?from=digest&date=060421)

**Comment by xenmayer** [comment]
[Жизнь как один большой факап](https://vc.ru/life/215597-zhizn-kak-odin-bolshoy-fakap?from=digest&date=060421)

**Comment by xenmayer** [comment]
[Я интроверт — не люблю разговаривать по телефону. Поэтому я создал робота Машу — теперь она отвечает на все звонки](https://vc.ru/tribuna/226834-ya-introvert-ne-lyublyu-razgovarivat-po-telefonu-poetomu-ya-sozdal-robota-mashu-teper-ona-otvechaet-na-vse-zvonki?from=digest&date=060421)

**Comment by AlexMzuev** [comment]
[Microsoft Edge поднялся на второе место по популярности среди десктопных браузеров для Windows](https://www.playground.ru/misc/news/microsoft_edge_podnyalsya_na_vtoroe_mesto_po_populyarnosti_sredi_desktopnyh_brauzerov_dlya_windows-1101408)

**Comment by dmitryplyaskin** [comment]
Почему Макс так много обещает и ничего не делает? Предлагаю публично поднять этот вопрос

**Comment by dmitryplyaskin** [comment]
Предлагаю обсудить важный вопрос.
В последнее время Максим много обещает, но ничего не делает. Монополия, статьи, свой пет проджект на effector, он ничего не делает. Как думаете, что можно с этим сделать?

**Comment by anton-okolelov** [comment]
https://www.opennet.ru/opennews/art.shtml?num=54918

**Comment by anton-okolelov** [comment]
Эротические фантазии https://t.me/crossjoin/79

**Comment by anton-okolelov** [comment]
https://techbeacon.com/security/cryptominers-flooding-github-other-cloudy-dev-services

**Comment by xenmayer** [comment]
Видео: https://youtu.be/w1bhq94q724
Аудио (будет доступно 10.04 в 6:00): https://soundcloud.com/znprod/107-mainim-v-paiplainakh-uchimsya-na-svoikh-oshibkakh
