### ISSUE TITLE
Темы для выпуска. Цинковый прод #084 [29.10.2020]

### ISSUE THREAD

**Issue by xenmayer** [znprod/stream-topics#3]
В этот выпуск к нам в гости придет **Максим Фролов** _[Senior Project Manager, IT delivery manager, KMP]_.

Поговорим с ним на тему `Как управлять работой, а не людьми?`. 

Как организовать работу команды так, чтобы всё успевать. Как правильно взаимодействовать с бизнесом при постановке задач. Отдел как часть общей системы

Предлагайте свои вопросы и темы для обсуждения с нашим гостем.

**Comment by NRopot** [comment]
Более технический вопрос чем организационный. Хотелось бы послушать про схемы silent refresh token в целом(плюсы, минусы, трудности...) и относительно недавнюю фичу хрома с SameSite cookie (https://www.chromestatus.com/feature/5088147346030592). Проблемы имплементации «тихого обновления» через iframe в разных браузерах, может быть у кого-то был интересный опыт с этим.

**Comment by RinatValiullov** [comment]
Интересно было бы послушать про **управление рисками**

**Comment by githubjeka** [comment]
Faker is archived. Read the reasons behind this decision here: https://marmelab.com/blog/2020/10/21/sunsetting-faker.html

**Comment by xenmayer** [comment]
Видео эфира: https://youtu.be/AkWtz47Wo9Y
