### ISSUE TITLE
Темы для выпуска #112 (13 мая) про канбан-метод с Максом Фроловым

### ISSUE THREAD

**Issue by RinatValiullov** [znprod/stream-topics#34]
Предлагайте свои вопросы и темы к эфиру 🎤
А ведущие обязательно их озвучат. И постараются ответить на все предложенные вопросы 🔈

**Comment by artjomka** [comment]
https://betterprogramming.pub/the-worst-question-you-can-ask-a-software-developer-ddbcd5956eb4
Худший вопрос программисту и я с этим согласен

**Comment by DevNulPavel** [comment]
https://habr.com/ru/news/t/557152/
Фиг знает, похоже на какой-то троллинг от компании Tesla)

**Comment by xenmayer** [comment]
Аудио: https://soundcloud.com/znprod/112-govorim-o-kanban-metode-s-maksimom-frolovym
Видео: https://youtu.be/9Ms6tx2Sq-4
