### ISSUE TITLE
Темы для выпуска #116  (10 июня)

### ISSUE THREAD

**Issue by anton-okolelov** [znprod/stream-topics#38]
Пишите тут чо хотите )

**Comment by alekspickle** [comment]
https://docs.microsoft.com/en-us/windows/package-manager/

**Comment by AlexMzuev** [comment]
https://itc.ua/news/apple-vyplatila-milliony-dollarov-kompensaczii-studentke-posle-togo-kak-sotrudniki-servisnogo-czentra-opublikovali-ee-intimnye-foto/

**Comment by xenmayer** [comment]
[Росгвардия заплатит более 300 млн рублей за IT-систему контроля за оружием](https://habr.com/ru/news/t/561366/)

**Comment by zenwarr** [comment]
[ Что делать, если всё ваше существо противится поставленной задаче ](https://habr.com/en/company/timeweb/blog/561434/)

**Comment by anton-okolelov** [comment]
[мода на canvas вместо html](https://habr.com/ru/company/ruvds/blog/560736/)

**Comment by anton-okolelov** [comment]
[Приложение для поимки убийц и наркоторговцев ](https://www.rbc.ru/society/08/06/2021/60bf3c3e9a794763b3a8047d?from=from_main_11)

**Comment by zenwarr** [comment]
[ Fastmail поддалась требованиям Роскомнадзора и закрыла регистрацию для пользователей из России ](https://habr.com/en/news/t/561872/)

**Comment by ygrishaev** [comment]
Теперь вам будет проще накопить на робособаку!

https://vc.ru/tech/257170-kitayskaya-kompaniya-vypustila-robopsa-kompanona-za-2700-v-27-5-raz-deshevle-chem-spot-ot-boston-dynamics

**Comment by ygrishaev** [comment]
История исчезновения самокатов в СПб за 1 день

https://t.me/mashmoyka/6929

https://vc.ru/transport/256472-hronologiya-ot-draki-do-zamorozki-chto-proizoshlo-vokrug-servisov-arendy-elektrosamokatov-v-peterburge-za-mesyac

**Comment by ygrishaev** [comment]
Яндекс анонсировал Y1 — обновлённый поиск с более 2100 улучшений

https://tproger.ru/news/jandeks-anonsiroval-y1-obnovljonnyj-poisk-s-bolee-2100-uluchshenij/

**Comment by xenmayer** [comment]
Видео: https://youtu.be/a1aLCmZxMvU
Аудио (доступно с 6:00 12.06): https://soundcloud.com/znprod/116-kanvas-khtml-i-troyan-dlya-prestupnikov/s-h3oBB5IdONu

**Comment by q-tea** [comment]
[PCIe RAM диск на базе DDR памяти](https://habr.com/ru/post/567742/)
