### ISSUE TITLE
Темы для выпуска. Цинковый прод #085 [05.11.2020]

### ISSUE THREAD

**Issue by xenmayer** [znprod/stream-topics#4]
Пишите темы, кидайте ссылки, вопросы - всё, что хотели бы обсудить в следующем выпуске!

**Comment by ovr** [comment]
- [GitHub опубликовал судебное решение, имеющее отношение к блокировке youtube-dl](https://www.opennet.ru/opennews/art.shtml?num=53990)
- [Я пришел на собеседование с лайвкодингом — и меня с позором размазали](https://habr.com/ru/company/vdsina/blog/524768/)

**Comment by xenmayer** [comment]
[Generating fake resumes with GPT-3](https://gpt3.jsonresume.org/)

**Comment by xenmayer** [comment]
[New Metric: the Distance of Coupling](https://www.yegor256.com/2020/10/27/distance-of-coupling.html)

**Comment by githubjeka** [comment]
https://habr.com/ru/post/526474/

**Comment by xenmayer** [comment]
Видео: https://youtu.be/JYaQxnmpvPE
