### ISSUE TITLE
Темы для выпуска #119 (1 июля)

### ISSUE THREAD

**Issue by xenmayer** [znprod/stream-topics#41]
Привет! Ждем Ваши вопросы и темы к эфиру 🎙.

**Comment by artjomka** [comment]
Гугол предоставил тулзу котороая будет подсчитывать зарплату для удаленьщиков в разных регионах
https://www.cnet.com/news/google-rolls-out-tool-to-show-its-employees-compensation-changes-for-transferring-offices/

**Comment by NChechulin** [comment]
[Chrome откладывает отказ от cookies до 2023](https://www.opennet.ru/opennews/art.shtml?num=55387)

**Comment by stryaponoff** [comment]
PSR и Twig в Битриксе
https://twitter.com/5minphp/status/1407636431267323906?s=20

**Comment by ygrishaev** [comment]
Конфликты в посёлке для программистов

https://vc.ru/story/260479-platite-i-vse-budet-rabotat-zhiteli-poselka-programmistov-pod-kirovom-uzhe-dva-goda-zhivut-v-konflikte-s-osnovatelem

**Comment by xenmayer** [comment]
[What is your approach to low-priority bugs?](https://sqa.stackexchange.com/questions/47630/what-is-your-approach-to-low-priority-bugs?utm_source=Iterable&utm_medium=email&utm_campaign=the_overflow_newsletter)

**Comment by xenmayer** [comment]
[Sony Music добилась в суде блокировки пиратских сайтов на уровне DNS-резолвера Quad9](https://www.opennet.ru/opennews/art.shtml?num=55385)

**Comment by xenmayer** [comment]
[Ошибка в BIND 9.16.17, приводящая к неверной обработке символа W в DNS-запросах](https://www.opennet.ru/opennews/art.shtml?num=55373)

**Comment by xenmayer** [comment]
[Инфраструктурой российского DoubleVPN завладели зарубежные спецслужбы](https://habr.com/ru/news/t/565420/)

**Comment by xenmayer** [comment]
[Microsoft и GitHub представили нейросетевого помощника программиста Copilot](https://habr.com/ru/news/t/565376/)

**Comment by xenmayer** [comment]
[В сети продают базу данных LinkedIn на 700 млн записей](https://habr.com/ru/news/t/565360/)

**Comment by hack3p** [comment]
Your AI pair programmer
https://copilot.github.com

**Comment by hack3p** [comment]
Lego 

https://tjournal.ru/404236

**Comment by xenmayer** [comment]
Видео: https://youtu.be/fJK9mz-L7Fc
Аудио (будет доступно с 6:00 03.07): https://soundcloud.com/znprod/119-strim-sebya-avtokod-ot-melokomyagkikh/s-Jwq31oHLzpH
