### ISSUE TITLE
 Темы для выпуска #120 (8 июля) 

### ISSUE THREAD

**Issue by hack3p** [znprod/stream-topics#42]

**Comment by hack3p** [comment]
Audacity personal data
https://habr.com/ru/news/t/566316/

**Comment by ygrishaev** [comment]
В Исландии проверили четырёхдневную рабочую неделю на трёх тысячах работающих жителей — продуктивность не снизилась 

https://vc.ru/office/266821-v-islandii-proverili-chetyrehdnevnuyu-rabochuyu-nedelyu-na-treh-tysyachah-rabotayushchih-zhiteley-produktivnost-ne-snizilas

**Comment by stryaponoff** [comment]
Разработчики критикуют GitHub Copilot: ИИ генерирует цитаты из проектов с открытым исходным кодом и выдает ключи API

https://habr.com/ru/news/t/566184/

**Comment by anton-okolelov** [comment]
Openspace добавляет стресса. [Научное исследование](https://www.abc.net.au/news/2021-07-06/open-plan-office-noise-increase-stress-worse-mood-new-study/100268440 )

**Comment by anton-okolelov** [comment]
[Чел предлагает сделать группируемые комиты](http://blog.danieljanus.pl/2021/07/01/commit-groups/)

**Comment by DevNulPavel** [comment]
[Вторая редакция патчей для ядра Linux с поддержкой языка Rust](https://www.opennet.ru/opennews/art.shtml?num=55443)
Верной дорогой идем в светлое будущее

**Comment by caspirt** [comment]
[Бывшие сотрудники Google запустили первый платный поисковик](https://habr.com/ru/company/gms/blog/566030/)

**Comment by NChechulin** [comment]
[GitHub Copilot AI Is Generating And Giving Out Functional API Keys](https://fossbytes.com/github-copilot-generating-functional-api-keys/)

**Comment by NChechulin** [comment]
При обучении GitHub Copilot использовались **все** открытые репозитории, вне зависимости от лицензии. Часть общественности негодует.

_Ссылки нема, если найду/кинут, то добавлю_

**Comment by AlexMzuev** [comment]
[Работник Microsoft украл более 10 миллионов долларов с помощью подарочных карт Xbox](https://www.bloomberg.com/features/2021-microsoft-xbox-gift-card-fraud/)

**Comment by xenmayer** [comment]
Видео: https://youtu.be/SmX19dZmof4
Аудио (будет доступно с 6:00 10.07): https://soundcloud.com/znprod/120-chetyrekhdnevnaya-rabochaya-nedelya-zashkvar-audacity/s-dv8QGD9n1UL
