### ISSUE TITLE
Темы для выпуска #121 (15 июля)

### ISSUE THREAD

**Issue by xenmayer** [znprod/stream-topics#43]
Привет! Ждем Ваши вопросы и темы к эфиру 🎙.

**Comment by caspirt** [comment]
[Владелец TikTok отменит обязательные для сотрудников переработки по выходным](https://habr.com/ru/news/t/566976/)

**Comment by caspirt** [comment]
[Накопленные человечеством знания исчезают из-за «битых» ссылок — страдают даже научные статьи и документы](https://vc.ru/future/268209-nakoplennye-chelovechestvom-znaniya-ischezayut-iz-za-bityh-ssylok-stradayut-dazhe-nauchnye-stati-i-dokumenty)

**Comment by RinatValiullov** [comment]
I'm back.

[Why Did We Ever Think the First Programming Language Didn't Matter?](https://cacm.acm.org/blogs/blog-cacm/253393-why-did-we-ever-think-the-first-programming-language-didnt-matter/fulltext)

**Comment by AlexMzuev** [comment]
[China’s “Involuted” Generation](https://www.newyorker.com/culture/cultural-comment/chinas-involuted-generation)

**Comment by AlexMzuev** [comment]
[Microsoft рассказала о собственном Linux-дистрибутиве CBL-Mariner](https://habr.com/ru/company/itsumma/news/t/567246/)

**Comment by AlexMzuev** [comment]
[Доступна документо-ориентированная СУБД MongoDB 5.0](https://www.opennet.ru/opennews/art.shtml?num=55481)

**Comment by AlexMzuev** [comment]
[Представлена реализация Tor на языке Rust, которая в будущем заменит вариант на Си](https://opennet.ru/opennews/art.shtml?num=55461)

**Comment by xenmayer** [comment]
[Президент США Джо Байден подписал указ об ограничении монополии ИТ-компаний в стране](https://vc.ru/legal/268253-prezident-ssha-dzho-bayden-podpisal-ukaz-ob-ogranichenii-monopolii-it-kompaniy-v-strane?from=digest&date=130721)

**Comment by xenmayer** [comment]
[Arm назвала новым законом Мура производительность на ватт](https://habr.com/ru/news/t/567692/)

**Comment by caspirt** [comment]
[Как трёх программистов уволили из-за единственного сбоя в приложении](https://habr.com/ru/company/itsoft/blog/567826/)

**Comment by anton-okolelov** [comment]
83% рзрабов выгорают https://www.usehaystack.io/blog/83-of-developers-suffer-from-burnout-haystack-analytics-study-finds

**Comment by xenmayer** [comment]
Аудио (будет доступно 17.07 с 6:00): https://soundcloud.com/znprod/121-uvolneniya-programmistov-pererabotki-tiktoka-rinat-vernulsya/s-WHQESypEdzn
Видео: https://youtu.be/oC8lX1DPTnA
