### ISSUE TITLE
Темы для выпуска #122 (22 июля)

### ISSUE THREAD

**Issue by hack3p** [znprod/stream-topics#44]

**Comment by DevNulPavel** [comment]
[Когнитивные искажения с примерами для айтишников](https://habr.com/ru/company/karuna/blog/555270/comments/)
Осмелюсь предложить тему))

**Comment by xenmayer** [comment]
[У петербуржца украли телефон с установленными Госуслугами, а через полтора года на него оформили кредиты на 1 млн рублей](https://vc.ru/services/271400-u-peterburzhca-ukrali-telefon-s-ustanovlennymi-gosuslugami-a-cherez-poltora-goda-na-nego-oformili-kredity-na-1-mln-rubley?from=digest&date=200721)

**Comment by RinatValiullov** [comment]
За что боролись, на то и ...

[Каждому лицу по… баллу, или Как работает система социальной оценки граждан Китая](https://habr.com/ru/company/itsoft/blog/568854)

**Comment by anton-okolelov** [comment]
[уроки гуглера] (https://swizec.com/blog/what-i-learned-from-software-engineering-at-google/)

**Comment by anton-okolelov** [comment]
[чек лист для работы в новой команде](https://trstringer.com/20-questions-for-new-software-team/)

**Comment by q-tea** [comment]
[PCIe RAM диск на базе DDR памяти](https://habr.com/ru/post/567742/)

**Comment by RinatValiullov** [comment]
@DevNulPavel 

[#072 Когнитивные искажения.](https://youtu.be/uh5_gtQ9NH8)

**Comment by xenmayer** [comment]
Видео: https://youtu.be/L5YRhKVYifk
Аудио (доступно с 6:00 24.07): https://soundcloud.com/znprod/122-baly-ukradennyy-telefon-reshenie-konfliktov/s-N1P6lf98GQw
