### ISSUE TITLE
Темы для выпуска #124

### ISSUE THREAD

**Issue by anton-okolelov** [znprod/stream-topics#46]
Предлагай прям ща

**Comment by anton-okolelov** [comment]
![Uploading FB_IMG_1628087129224.jpg…]()

**Comment by anton-okolelov** [comment]
![FB_IMG_1628087129224](https://user-images.githubusercontent.com/12091051/128198652-e4034898-8f71-42e0-901b-accaeebc0da3.jpg)

**Comment by anton-okolelov** [comment]
Пустой пакет npm с 700к загрузок

**Comment by anton-okolelov** [comment]
[Новые команды git](https://www.banterly.net/2021/07/31/new-in-git-switch-and-restore/)

**Comment by AlexMzuev** [comment]
[SO опять всех спросил и графиков нарисовал](https://insights.stackoverflow.com/survey/2021)

**Comment by AlexMzuev** [comment]
[Is Rocky Linux the new CentOS?](https://www.cloudsavvyit.com/13092/is-rocky-linux-the-new-centos/)

**Comment by kpblc** [comment]
Amazon стал использовать «умные» камеры для контроля водителей доставки — нейросеть определяет их зарплаты и рейтинг

https://dtf.ru/hard/817370-amazon-stal-ispolzovat-umnye-kamery-dlya-kontrolya-voditeley-dostavki-neyroset-opredelyaet-ih-zarplaty-i-reyting

**Comment by AlexMzuev** [comment]
[Почему я отказался от 18 тысяч долларов по баунти-программе Apple](https://habr.com/ru/post/570064/)

**Comment by AlexMzuev** [comment]
[OpenAI выпустила язык программирования для разработки нейросетей](https://forklog.com/openai-vypustila-yazyk-programmirovaniya-dlya-razrabotki-nejrosetej/)

**Comment by xenmayer** [comment]
Видео: https://youtu.be/L5YRhKVYifk
Аудио: https://soundcloud.com/znprod/124-so-poschital-bigdata-uvolila/s-LGax4yebqOA
