### ISSUE TITLE
Темы эфира 125 (12 августа)

### ISSUE THREAD

**Issue by VladKapitan** [znprod/stream-topics#47]
https://www.ixbt.com/news/2021/08/10/xiaomi-predstavila-robosobaku-po-imeni-cyberdog.html

**Comment by anton-okolelov** [comment]
Apple будет смотреть ваши фотки
https://www.eff.org/deeplinks/2021/08/apples-plan-think-different-about-encryption-opens-backdoor-your-private-life

**Comment by artjomka** [comment]
https://habr.com/ru/post/571342/
Человек нахуячил сложного кода в тестовом задание и очень растроился от фитбяка

**Comment by AlexMzuev** [comment]
[ИТ-компания наняла морского пехотинца, чтобы тренировать удалённых сотрудников](https://dev.by/news/it-kompaniya-nanyala-morskogo-pehotintsa-chtoby-trenirovat-udalyonnyh-sotrudnikov)

**Comment by anton-okolelov** [comment]
[Всё, можно увольняться, роботы заменят программеров](https://vc.ru/dev/280281-openai-predstavila-instrument-codex-on-perevodit-angliyskiy-tekst-v-programmnyy-kod)

**Comment by Worldbug** [comment]
Гос инициатива которая погубит российскую микроэлектроннику 

новость - https://www.cnews.ru/news/top/2021-07-19_glavnyj_razrabotchik_rossijskih
правки в законе - https://regulation.gov.ru/p/117387
разбор - https://youtu.be/t0Ha52GMZoc

**Comment by xenmayer** [comment]
video: https://www.youtube.com/watch?v=RTJ2Jf2deC0
audio: https://soundcloud.com/znprod/125-robosobaka-xiaomi-roboty-zamenyat-programmista-morskie-pekhotintsy/s-MbYi27oOGzz
