### ISSUE TITLE
Темы эфира #126 (19 августа)

### ISSUE THREAD

**Issue by evgwed** [znprod/stream-topics#48]
> Как я попал в ThoughtWorks или образцовое интервью
> https://stringconcat.com/ru/how-to-be-thoughtworker/

Собеседование нормального человека, а не вот эти ваши "Сколько пенисных мячей поместятся в жопу водителя автобуса" и копирование вопросов google. Контора основана Мартином Фаулером

**Comment by evgwed** [comment]
> Amazon будет отслеживать движения мышки на компьютерах сотрудников для безопасности данных клиентов — Vice
> https://vc.ru/office/281293-amazon-budet-otslezhivat-dvizheniya-myshki-na-kompyuterah-sotrudnikov-dlya-bezopasnosti-dannyh-klientov-vice

а затронет ли жто программистов в Amazon?

**Comment by AlexMzuev** [comment]
[Антипираты попросили Google заблокировать 127.0.0.1](https://xakep.ru/2021/08/10/127-0-0-1-piracy/)

**Comment by xenmayer** [comment]
[Что такое «метавселенная», которую строят Марк Цукерберг, Сатья Наделла и Тим Суини — и зачем это нужно](https://vc.ru/future/281044-chto-takoe-metavselennaya-kotoruyu-stroyat-mark-cukerberg-satya-nadella-i-tim-suini-i-zachem-eto-nuzhno?from=digest&date=170821)

**Comment by xenmayer** [comment]
[В США представили законопроект об ограничении контроля Apple и Google над магазинами приложений](https://vc.ru/services/281020-v-ssha-predstavili-zakonoproekt-ob-ogranichenii-kontrolya-apple-i-google-nad-magazinami-prilozheniy?from=digest&date=170821)

**Comment by xenmayer** [comment]
[Российским клиентам Visa дали возможность удалять данные карт со сторонних сайтов](https://habr.com/ru/news/t/572746/)

**Comment by xenmayer** [comment]
[«Почта России» создает крупную IT-компанию](https://habr.com/ru/news/t/573362/)

**Comment by AlexMzuev** [comment]
[BostonDynamics показала площадку «для паркура», где тестируют роботов. Там они делают сальто назад и «гордятся» успехами](https://tjournal.ru/tech/425625-bostondynamics-pokazala-ploshchadku-dlya-parkura-gde-testiruyut-robotov-tam-oni-delayut-salto-nazad-i-gordyatsya-uspehami)

**Comment by AlexMzuev** [comment]
[Apple выпустила FAQ по фиче для "защиты детей"](https://www.apple.com/child-safety/pdf/Expanded_Protections_for_Children_Frequently_Asked_Questions.pdf)

**Comment by xenmayer** [comment]
[ФСБ возбудила дело о попытке взлома сетевым инженером структуры «Ростеха»](https://habr.com/ru/news/t/573548/)

**Comment by artjomka** [comment]
Вопросы компании на собеседовании
https://github.com/kix/reverse-interview/blob/master/README.md

**Comment by xenmayer** [comment]
Audio: https://soundcloud.com/znprod/126-obraztsovyy-sobes-metavselennykh
Video: https://youtu.be/l6dr1FmGEPE
