### ISSUE TITLE
Темы для выпуска. Цинковый прод #086 [12.11.2020]

### ISSUE THREAD

**Issue by hack3p** [znprod/stream-topics#5]

**Comment by Petrovvich** [comment]
Обсудите эту статью про сравнение производительности Rust и C++ http://tempesta-tech.com/blog/fast-programming-languages-c-c++-rust-assembly
Да и вообще можете за кейсы увеличения производительности кода на проде из своего опыта потрещать.

**Comment by xenmayer** [comment]
[GitHub Source Code Leak](https://resynth1943.net/articles/github-source-code-leak/)

**Comment by githubjeka** [comment]
Про очереди https://www.hillelwayne.com/post/queueing-prism/

Описана ситуация когда все воркеры заняты, а задачи ждут обслуживания. Решение в лоб - добавлю ка я новых 10 воркеров.  Но без теории сложно оценить сколько точно хватит для работы очереди без задержек...

**Comment by paulmixxx** [comment]
La'Cringe :joy: 
https://habr.com/ru/company/habr_career/blog/522568/
https://habr.com/ru/company/habr_career/blog/523740/
https://habr.com/ru/company/habr_career/blog/524754/

**Comment by evgwed** [comment]
[Я стал думать над мелочами в коде, и уничтожил все желание программировать](https://habr.com/ru/company/vdsina/blog/525738)

Годная статья о том, как сильно можно заморочиться при запуске нового проекта, как пытаешься сделать круто, но нормы принятые в сообществе, не дают этого делать. 

Вот, например, отличное высказывание про комментарии:
> Если всех этих вещей тебе мало, что бы объяснить, как мне использовать твой код, документация тебе не поможет. Она просто замаскирует твою некомпетентность.

Или вот про синдром самозванца:
> Когда я пишу код не так, как принято в .net-сообществе, мне все время кажется: «Что ты делаешь, идиотина?! Взрослые дяди со всем уже давно разобрались, ты же не думаешь, что ты умнее их?». Как русский человек, я не привык думать, что моё мнение хоть чего-то стоит. В такие моменты мне кажется, что я наваял себе воздушных замков, всё для себя логически объяснил, но всё равно тупой и полностью не прав.

**Comment by ovr** [comment]
- (Сертификаты Let's Encrypt перестанут восприниматься на 33% Android-устройств)[https://www.opennet.ru/opennews/art.shtml?num=54043]
- (Composer 2: Что нового?)[https://habr.com/ru/post/524916/]

**Comment by anton-okolelov** [comment]
[kphp опять](https://habr.com/ru/company/vk/blog/527420/)

**Comment by evgwed** [comment]
[Клуб анонимных Дедов Морозов 2020–2021 на Habr](https://habr.com/ru/post/526500/) или как влоить немало денег для другого человека и получить в результате:
- [набор старых и ненужных журналов "Мир ПК"](https://habr.com/ru/post/481118/#comment_21204646)
- [дулю](https://habr.com/ru/post/205232/#comment_7139954)
- [ничего](https://habr.com/ru/post/481118/#comment_21104082)

На самом деле можно просто обсудить как вы относитесь к игре "Тайный санта", опыт в коллективе коллег.

**Comment by githubjeka** [comment]
[Использование Rust при масштабировании в Elixir для 11 миллионов одновременных пользователей](https://blog.discord.com/using-rust-to-scale-elixir-for-11-million-concurrent-users-c6f19fc029d3)

**Comment by Petrovvich** [comment]
WhatsApp запустил платежи через себя в Индии
https://blog.whatsapp.com/send-payments-in-india-with-whatsapp/?lang=en
Прост угарный сайт, симулирующий жижу
https://paveldogreat.github.io/WebGL-Fluid-Simulation/

**Comment by githubjeka** [comment]
![image](https://user-images.githubusercontent.com/874234/98898833-8c87de00-24bf-11eb-9202-fc0dceb05696.png)

**Comment by evgwed** [comment]
Трекер Amoung US на основе Notion: 
https://thomasjfrank.com/templates/among-us-notion-template/

**Comment by evgwed** [comment]
> Автор httpsoft/http-message, Евгений Зюбин, вероятно присоединится к команде фулл-тайм если/когда это позволит пополнение фонда. Если вы или ваша компания хотите получить Yii 3 раньше, можете помочь.

https://habr.com/ru/post/527634/

**Comment by xenmayer** [comment]
Видео: https://www.youtube.com/watch?v=osFfa4ZUPHA
