### ISSUE TITLE
Темы эфира #132 (30 сентября)

### ISSUE THREAD

**Issue by hack3p** [znprod/stream-topics#53]

**Comment by RinatValiullov** [comment]
В нашем любимом чатике произошёл такой диалог:

<details>
  <summary>Диалог</summary>

<em>- Ну в компанию ***, если бы он был в ней директором я бы не попал просто потому, что неприятен ему)</em>

<em>- и что в этом плохого? если одному человеку не нравится другой, он как работодатель может тебя просто не брать на работу</em>

</details>

<br>
<b>Отсюда возникли вопросы следующего характера. Хотелось бы услышать мнение каждого ведущего отдельно.</b>

- Как вы считаете, правильно ли разделять кандидатов при найме на работу по каким-то своим одному лишь Богу(Повелителю, Властелину, Вождю, Царю, Владыке, etc) и тебе известным признакам? Признакам, которые не проверить, не просчитать. Скорее предпочтениям. Вот просто не понравился парень/девушка лично интервьюеру и не будем брать его. Эдакий "фейсконтроль" в айти.

- Если такой "механизм" отбора присутствует, то какие конкретно личные критерии к кандидату вы предъявляете, парни? Что должно быть в человеке **так/не так**, чтобы он **прошёл/не прошёл**? Будет ещё лучше, если вспомните примеры из реального опыта.

- Не наносит ли вред в дальнейшем подобное **разделение** тем ребятам, которые не прошли и сами того не поняли почему? А что в этом случае насчёт репутации самой компании?

- Что и как бы вы сказали кандидату, который не понравился, если бы задача стояла быть максимально честным и прямым? (вопрос скорее теоретический, потому что на практике в лоб человеку никто подобного говорить, конечно же, не будет)  

  - А какой фидбек вы обычно даёте в реальной практике подобным кандидатам?  

- Как быть в ситуации, когда мнения о человеке разделились поровну? При условии, что собеседование проводят несколько человек.

- Что вы вкладываете в такое понятие как "адекватность"? (часто слышу именно про этот критерий отбора). А также "душный" и "токсичный". Пора уже дать этим характеристикам ЧЁТКИЕ и ПОНЯТНЫЕ для всех определения 😄  Если, конечно, такое вообще возможно сделать...



' Надо добавить, что наши _гипотетические кандидаты_ при прочих равных условиях имеют одинаковый набор и уровень навыков, необходимых для того, чтобы быть принятыми. Проще говоря, они все подходят в техническом плане.
'' Если кому-то захочется разделить в плане "джун-сеньор", то можно пройтись по каждому отдельно. А то вдруг есть какие-то различия между ними. (это не моё мнение, что различаются как-то; а просто один из возможных вариантов). Если их нет, то значит нет.

**Comment by anton-okolelov** [comment]
https://habr.com/ru/company/otus/blog/580264/

**Comment by anton-okolelov** [comment]
https://t.me/crossjoin/114

**Comment by anton-okolelov** [comment]
[яндекс поиск теперь везде будет по умолчанию](https://lenta.ru/news/2021/09/27/yandex/)

**Comment by anton-okolelov** [comment]
[таксист-питонист](https://roem.ru/23-09-2021/286803/yandex-praktikum-taxi/)

**Comment by anton-okolelov** [comment]
[обман распознавания лиц](https://nplus1.ru/news/2021/09/27/makeup)

**Comment by xenmayer** [comment]
[Предсказал будущее интернета в 90-ых и пропал, когда его прогнозы стали сбываться: история Филипа Агре](https://vc.ru/story/296536-predskazal-budushchee-interneta-v-90-yh-i-propal-kogda-ego-prognozy-stali-sbyvatsya-istoriya-filipa-agre?from=digest&date=280921)

**Comment by xenmayer** [comment]
[Microsoft пообещала, что обновление Skype сделает его плавным](https://habr.com/ru/news/t/580536/)

**Comment by anton-okolelov** [comment]
[Троллинг кафки](https://tjournal.ru/internet/446695-programmisty-zadayut-voprosy-ob-apache-kafka-na-posvyashchennom-francu-kafke-sabreddite-im-otvechayut-otsylkami-na-process)

**Comment by AlexMzuev** [comment]
[Михаил Мишустин «анонсировал» российский аналог GitHub](https://habr.com/ru/news/t/579184/)

**Comment by AlexMzuev** [comment]
[Срок действия корневого сертификата Let's Encrypt истек. Миллионы устройств останутся без интернета](https://habr.com/ru/news/t/580818/)

**Comment by AlexMzuev** [comment]
[Аналитик EPAM убит в собственном доме](https://habr.com/ru/news/t/580754/)

**Comment by xenmayer** [comment]
Audio: https://soundcloud.com/znprod/132-taksist-pitonist/s-pgHsVQPN7Zw?si=82d3ed825a884284919638e2e03e59bc
Video: https://youtu.be/8jq9mi_ZZbY
