### ISSUE TITLE
Темы эфира #134 (14 октября)

### ISSUE THREAD

**Issue by xenmayer** [znprod/stream-topics#56]
Заходи, торопись, покупай живопись! Ждем ваши темы друзья! 😊

**Comment by anton-okolelov** [comment]
[фейсбук забанил программиста нисхуя](https://slate.com/technology/2021/10/facebook-unfollow-everything-cease-desist.html)

**Comment by anton-okolelov** [comment]
[json -  это сложно](https://seriot.ch/projects/parsing_json.html)

**Comment by artjomka** [comment]
https://whoisnnamdi.com/never-enough-developers/ судя по статистике программистов  не будет хватать и треть людей сьябывают из айтишечки через 10+ лет

**Comment by artjomka** [comment]
http://www.bennorthrop.com/Essays/2021/always-do-extra.php 
Интересная статья потенциально о том как можно не выгореть в программировании

**Comment by AlexMzuev** [comment]
[Как служится в белорусской ИТ-роте: честный рассказ дембеля](https://habr.com/ru/company/lanit/blog/581480/)
