### ISSUE TITLE
Выпуск #87. В гостях Виталий Брагилевский. Темы для выпуска. [19.11.2020]

### ISSUE THREAD

**Issue by hack3p** [znprod/stream-topics#6]

**Comment by RinatValiullov** [comment]
Было бы интересно, если бы Виталий рассказал немного про *соответствие (изоморфизм) Карри - Ховарда*.
В одном (молодом) подкасте он вскользь коснулся темы, что всякая программа подобна доказательству теоремы, но не упоминал эту эквивалентность.

**Comment by githubjeka** [comment]
Когда стоит применять функциональное, а когда объектно-ориентированное программирование?
Если по сути они отличаются только [диспетчеризацией](https://en.wikipedia.org/wiki/Dynamic_dispatch) : ООП - диспетчеризация до вызова "метода", функциональное - после вызова функции, то почему большинство агитируют за функциональное? Или всё таки имеется **существенная** разница?

Попадались ли примеры, книги где функциональное и ООП живут совместно и дружно? (Рекомендации от Виталия).

**Comment by lFandoriNl** [comment]
Брагилевский упоминал в твиторах что подписался на нетфликс и спрашивал что смотреть то в нетфликсах этих ваших. Короче можете поболтать за фильмы/сериалы

**Comment by lFandoriNl** [comment]
Брагилевский лайкал фоточки природы в твиторах
Он чувствует себя угнетенным в каменных городах?

**Comment by zetroot** [comment]
Прогеры-хулиганы. Кто? Зачем? Есть ли польза?
https://m.habr.com/ru/news/t/528050/

**Comment by kattaris** [comment]
Самые востребованные в России ИТ-профессии
https://proglib.io/p/samye-vostrebovannye-v-rossii-it-professii-2020-11-16

**Comment by githubjeka** [comment]
[Вы безумны, остановитесь пока не поздно](https://habr.com/ru/post/528678/)

Что Виталий думает про курсы вайти?

**Comment by bobagold** [comment]
Мюнхен, Прага, Амстердам (офисы JetBrains - работодателя Виталия): что посмотреть, мнение о городах и планы переезда.

**Comment by bbtony** [comment]
Что там с веществами у Виталия? Судя по твиту, он проводил некое исследование))
