### ISSUE TITLE
Темы эфира #141 (25 ноября)

### ISSUE THREAD

**Issue by RinatValiullov** [znprod/stream-topics#62]
Ждём ваших тем, камрады. Да погорячее!

**Comment by RinatValiullov** [comment]
[Насколько убил клячу, настолько и уехал.](https://blog.jetbrains.com/phpstorm/2021/11/the-php-foundation)

**Comment by RinatValiullov** [comment]
[Кто бы мог подумать. Самое френдли коммьюнити...](https://www.opennet.ru/opennews/art.shtml?num=56208)

**Comment by xenmayer** [comment]
[Аудиоплеер Winamp обновил сайт и логотип и открыл регистрацию на бета-тестирование новой версии приложения](https://vc.ru/services/321755-audiopleer-winamp-obnovil-sayt-i-logotip-i-otkryl-registraciyu-na-beta-testirovanie-novoy-versii-prilozheniya?from=digest&date=231121)

**Comment by RinatValiullov** [comment]
[Квадратом меньше, квадратом больше. Подумаешь :man_shrugging: ](https://habr.com/ru/post/590663)

**Comment by RinatValiullov** [comment]
[А я говорил, читайте, что написано внизу мелким почерком!](https://habr.com/ru/company/itsoft/blog/590357)

**Comment by RinatValiullov** [comment]
[Здравствуйте, Вам звонят из службы безопасности банка.](https://habr.com/ru/company/itsoft/blog/590855)

**Comment by RinatValiullov** [comment]
[Анонсировали _убйцу NextJS_](https://twitter.com/remix_run/status/1462900248016130051)

<details>
<summary>Не открывать</summary>

Мнение автора может не совпадать с мнением ведущих подкаста "Цинковый прод"

</details>

**Comment by evgwed** [comment]
**Никита Попов уходит из PHP в Rust, грустили всей командой. PHP уже не торт, загнется?!**

JetBrains и другие компании инициировали создание фонда PHP
https://blog.jetbrains.com/phpstorm/2021/11/the-php-foundation/

Никита Попов, кроме PHP, долгое время контрибьютил в LLVM и Rust. И теперь решил переключить свою профессиональную деятельность на LLVM. Он все еще будет частью PHP-сообщества, но контрибьютить будет значительно меньше.

Это подтолкнуло на создание фонда PHP, цель которого — обеспечить развитие языка.

JetBrains, Automattic, Acquia, Laravel, Private Packagist, Symfony, Zend, Craft CMS, Tideways и PrestaShop объединили усилия и стали основателями и первыми финансовыми спонсорами фонда.

Первичная цель фонда — нанять part-time или full-time core разработчиков для работы на PHP.


_P.S.  не забудьте про @ в пхп_ 


UPD: Больше всех задонатил создатель Laravel - Taylor, вот кто больше всего переживает и у кого в php есть бабки 
![image](https://user-images.githubusercontent.com/6000708/143043636-243de1d0-7470-4b21-8d48-d6fe73bb0ead.png)

**Comment by RinatValiullov** [comment]
[Хватит эксплуатировать бедных джунишек!](https://vc.ru/promo/320245-rabotat-za-opyt)

**Comment by RinatValiullov** [comment]
[Разрабы оклемались.](https://www-infoworld-com.cdn.ampproject.org/c/s/www.infoworld.com/article/3640930/github-dev-productivity-is-back-to-pre-pandemic-levels.amp.html)

**Comment by anton-okolelov** [comment]
[Почему функции в php так странно называются](https://www.reddit.com/r/programming/comments/qzzrwi/php_creator_functions_were_named_to_fall_into/)

**Comment by evgwed** [comment]
[Самый оплачиваемый язык программирования Rust лишился важной части команды. Она ушла в знак протеста](https://www.cnews.ru/news/top/2021-11-23_samyj_oplachivaemyj_yazyk)

> Модераторы сообщества языка программирования Rust в полном составе оставили свои посты в знак протеста против действий основной команды разработчиков. Заявление об уходе они опубликовали на GitHub. Истинные причины такого решения неизвестны. Участники сообщества предполагают, что члены Core Team стали регулярно мешать им работать. Имена виновных в уходе модераторов не раскрываются. Пишущие на Rust программисты зарабатывают значительно больше своих коллег, использующих другие языки.

**Comment by AlexMzuev** [comment]
[Приложением «Дія» пользуются 10 млн пользователей. Вот какая зарплата у сотрудников](https://mc.today/prilozheniem-diya-polzuyutsya-10-mln-polzovatelej-vot-kakaya-zarplata-u-sotrudnikov/)

**Comment by AlexMzuev** [comment]
[Тысячи изображений, проданных как NFT, были опубликованы бесплатно](https://gagadget.com/business/89890-tyisyachi-izobrazhenij-prodannyih-kak-nft-byili-opublikovanyi-besplatno/)

**Comment by RinatValiullov** [comment]
_Философская тема. Ближе к концу подкаста самое то. На десерт😄_

[Мамкины анархисты опасны сами для себя.](https://www.jessesquires.com/blog/2021/11/24/reading-notes-abolition-of-work)

<blockquote>
Честно говоря, большую часть времени, проведенного в сфере высоких технологий, я разочаровался. Я часто чувствую себя полностью оторванным от работы, которую я делаю, от корпорации, в которой я работаю, и особенно от тех пустых и бесполезных «заявлений о миссии компании», которые руководители делали в том году, чтобы успокоить и мотивировать нас.
</blockquote>


<b>А если серьёзно, то доля правды в его словах присутствует. КМ, мы с тобой 💪 </b>

**Comment by RinatValiullov** [comment]
Антон, смотри что есть 🎆 

1.

[TiDB is an open source distributed HTAP database compatible with the MySQL protocol](https://github.com/pingcap/tidb)

[Wasm + Golang творят чудеса](https://github.com/pingcap/tidb/pull/13069) ===> [Нажми и посмотри в деле](https://play.tidb.io)

2.
[И про postgress мы не забыли](https://github.com/wasmerio/wasmer-postgres)

[Многообещающие результаты...](https://github.com/wasmerio/wasmer-postgres#benchmarks)

**Comment by RinatValiullov** [comment]
[Сам создаёт анкеты и берёт удалённые фото: в сети появились жалобы на дейтинг от «ВКонтакте»](https://daily.afisha.ru/news/57159-sam-sozdaet-ankety-i-beret-udalennye-foto-v-seti-poyavilis-zhaloby-na-deyting-ot-vkontakte)

**Comment by RinatValiullov** [comment]
["Языковой цирк"](https://grishaev.me/dont-mix-langs)

![image](https://user-images.githubusercontent.com/9755333/143459136-1611e367-2f44-4d0b-8350-72cc97a6e6db.png)

Парни, а вы что думаете? Согласны с автором?

**Comment by artjomka** [comment]
https://newsletter.pragmaticengineer.com/p/more-follow-up-hiring-market
Интересный обзор зарплат рыночка ЕС программистов и какие компании принимают или  не принимают какие-то шаги по удержанию
