### ISSUE TITLE
Цинковый митап #146 (30 декабря)

### ISSUE THREAD

**Issue by xenmayer** [znprod/stream-topics#68]
Тут опишем гостей и темы😉

**Comment by evgwed** [comment]
Позовите Рината под конец митапа поговорить о фильме Таксист 
![image](https://user-images.githubusercontent.com/6000708/147530779-34b3436b-8b26-4c99-aace-17143c2945a4.png)

**Comment by RinatValiullov** [comment]
> Позовите Рината под конец митапа поговорить о фильме Таксист ![image](https://user-images.githubusercontent.com/6000708/147530779-34b3436b-8b26-4c99-aace-17143c2945a4.png)



https://user-images.githubusercontent.com/9755333/147645601-fdbf4983-92fd-44fe-a397-37c93126a2de.mp4

**Comment by RinatValiullov** [comment]
Митап - 🔥  

Тян - :1st_place_medal:  

С НГ :fireworks:
