### ISSUE TITLE
Цинковый прод #147

### ISSUE THREAD

**Issue by evgwed** [znprod/stream-topics#69]
- [Взлом Госуслуг: утечка исходного кода](https://habr.com/ru/news/t/598121/) - кажется пора запретить git в разработке, говорят люди в проде открытой оставляют папку `.git` и злоумышленник выкачивает ее и палит все исходники. Пример `http://znprod.io/.git/`

**Comment by evgwed** [comment]
### Новое интуитивно понятное определение монады, заявка на победу, от Head of Data Science в 1С-Битрикс ([ссылка](https://www.facebook.com/permalink.php?story_fbid=1736604639869976&id=100005613702541))

![image](https://user-images.githubusercontent.com/6000708/147530273-0df543aa-9ba7-4664-baa8-14bca09f0b0b.png)

**Comment by AlexMzuev** [comment]
[Российский суд наложил оборотные штрафы на компании Google и Meta](https://xakep.ru/2021/12/24/google-meta-fine/)

**Comment by RinatValiullov** [comment]
Евгуэду объявляю благодарность 🌷 Спасибо, что перенял эту эстафетную палочку у меня, братка. А то парни мне ещё ЗП за прошлый месяц не выплатили 😄

 `*` И стикеров я так и не дождался...

И, конечно же, темка от меня:

[Теория Жоп](https://habr.com/ru/post/593173)

**Comment by prekel** [comment]
[Целый сайт про то, что C отстой](https://cmustdie.com/) ([или статья на Хабре](https://habr.com/ru/post/592233/)) от создателей https://github.com/znprod/stream-topics/issues/67#issuecomment-997425140

**Comment by xenmayer** [comment]
[Опрос «Работы.ру»: 71% россиян планируют сменить работу в 2022 году](https://habr.com/ru/news/t/599263/)

**Comment by AlexMzuev** [comment]
[Итоги года по версии Ебаного](https://ebanoe.it/2021/12/31/retrospective-and-awards-2/)

**Comment by AlexMzuev** [comment]
[7099 человеческих языков и 8945 языков программирования](https://habr.com/ru/company/timeweb/blog/598277/)

**Comment by AlexMzuev** [comment]
[Гражданская разведка разрушила государственную монополию на расследования](https://habr.com/ru/company/globalsign/blog/598675/)

**Comment by AlexMzuev** [comment]
[Как открыть 1500 шлагбаумов Москвы](https://habr.com/ru/company/postuf/blog/596293/)

**Comment by xenmayer** [comment]
[МЧС: астероид весом 30 млн тонн приблизится к Земле в 2029 году](https://habr.com/ru/news/t/599095/)

**Comment by RinatValiullov** [comment]
[«Работа — отстой для всех, от консерваторов до прогрессивных»](https://vc.ru/hr/340119-rabota-otstoy-dlya-vseh-ot-konservatorov-do-progressivnyh-chto-takoe-ideologiya-antiwork)

**Comment by RinatValiullov** [comment]
Кошмар, парни 😱 

[Почему PS5 нет в продаже, а видеокарты такие дорогие. Главное о дефиците полупроводников, который кончится ещё не скоро](https://tjournal.ru/tech/497059-pochemu-ps5-net-v-prodazhe-a-videokarty-takie-dorogie-glavnoe-o-deficite-poluprovodnikov-kotoryy-konchitsya-eshche-ne-skoro)

**Comment by xenmayer** [comment]
Audio: https://soundcloud.com/znprod/147-evgued-sozdal-rinat-poblagodaril
Video: https://youtu.be/XxrVztQ1HEA
