### ISSUE TITLE
Темы эфира #148 (13 января)

### ISSUE THREAD

**Issue by RinatValiullov** [znprod/stream-topics#70]
Исус некому сделать даже. Совсем от рук отбились без меня 😄 

Накидывайте темы в комментариях.

**Comment by RinatValiullov** [comment]
[Databases in 2021: A Year in Review](https://ottertune.com/blog/2021-databases-retrospective)

**Comment by kovuu** [comment]
https://habr.com/ru/post/598669/ Как заманить сотрудников обратно в офисы?

**Comment by kovuu** [comment]
https://safe.cnews.ru/news/top/2021-12-28_dyra_v_microsoft_azure_godami

**Comment by kovuu** [comment]
https://www.reddit.com/r/opensource/comments/rweact/is_open_source_hurting_business/ Открытый код и бизнес

**Comment by kovuu** [comment]
https://portswigger.net/daily-swig/researchers-discover-log4j-like-flaw-in-h2-database-console Очередная уязвимость в джава продукте

**Comment by RinatValiullov** [comment]
Парни, сохраните себе. Пригодится, когда вы наконец-то соберёте деньги на робопса.

[Инструкция: Как (теоретически) обезвредить робопса Boston Dynamics](https://tjournal.ru/tech/367765-instrukciya-kak-teoreticheski-obezvredit-robopsa-boston-dynamics)

**Comment by RinatValiullov** [comment]
[Сказка про антипаттерны: как мужики град стольный строили](https://habr.com/ru/post/645119)

**Comment by NChechulin** [comment]
https://rally.mozilla.org/current-studies/facebook-pixel-hunt/index.html

Файрфокс запустил кампанию по поиску трекеров фейсбука и анализу собираемых данных

**Comment by kovuu** [comment]
https://javascript.plainenglish.io/latest-web-development-and-javascript-trends-to-follow-in-2022-3d7f665aa5f7  Последние тенденции в веб-разработке и JavaScript в 2022 году

**Comment by kovuu** [comment]
https://bin.ua/news/finance/finances/272668-mozilla-priostanovila-priem-bitkoin-donatov-posle.html Mozilla приостановила прием биткоин-донатов после критики пользователей

**Comment by xenmayer** [comment]
[Extension to documentation your backend using AI](https://www.reddit.com/r/node/comments/s2fk8a/extension_to_documentation_your_backend_using_ai/)

**Comment by xenmayer** [comment]
[Репозиторий от Саши Майорова](https://github.com/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee)
