### ISSUE TITLE
Темы эфира #149 (20 января)

### ISSUE THREAD

**Issue by RinatValiullov** [znprod/stream-topics#71]
Темы, предложения и *прочую интересную хрень из мира айти и не только* предлагайте в комментариях.

**Comment by RinatValiullov** [comment]
DDD в Golang - новый хайп или неизбежность?

[How To Implement Domain-Driven Design (DDD) in Golang](https://programmingpercy.tech/blog/how-to-domain-driven-design-ddd-golang)

[How To Structure DDD in Go](https://programmingpercy.tech/blog/how-to-structure-ddd-in-go)

`*` Антон триггернётся

**Comment by omgpiu** [comment]
Я конечно слоупок, но все же.
Яндекс Браузер может переводить видео на русский язык.
 https://www.youtube.com/watch?v=C6owBIL0pAg 
Смотрим, делаем и потребляем контент

**Comment by RinatValiullov** [comment]
Поучительная статья

[How a Single Line of Code Made a 24-core Server Slower Than a Laptop](https://pkolaczk.github.io/server-slower-than-a-laptop)

**Comment by RinatValiullov** [comment]
Ну вот и всё. Поддержке AngularJS конец

[Discontinued Long Term Support for AngularJS](https://blog.angular.io/discontinued-long-term-support-for-angularjs-cc066b82e65a)

**Comment by RinatValiullov** [comment]
14 января нашему с вами любимому jQuery исполнилось 16 лет.
16 лет, <s>Карл</s> Антон! Да половина слушателей подкаста чуть старше, наверное. Как летит время...

[jQuery 2006](https://www.webdesignmuseum.org/web-design-history/jquery-2006)

**Comment by RinatValiullov** [comment]
_Насувайте_ там ему, мамкины тимлиды

[Записки юного TeamLead: Собеседования](https://habr.com/ru/post/599149)

**Comment by ignattru** [comment]
Пользуетесь ли вы дизайнерами БД, если да то какими?
Например вот: https://ondras.zarovi.cz/sql/demo/

PS: давно вас слушаю, красавчики!
PPS: А где мертвый комар?

**Comment by RinatValiullov** [comment]
[Клавиатура Charachorder: новое слово в вопросе ввода текста или странное изобретение?](https://habr.com/ru/company/selectel/blog/600941)

**Comment by RinatValiullov** [comment]
Подписываюсь под каждым словом!

[Почему Vivaldi никогда не будет создавать собственную криптовалюту](https://habr.com/ru/company/vivaldi/blog/645489)

**Comment by RinatValiullov** [comment]
Ебанистические статьи подвезли

[Жизнь как граф](https://habr.com/ru/post/645795)

`*` Антон, вот ты знал, что твоя жизнь - это система линий, связывающих какие-то *заданные* точки?

**Comment by kovuu** [comment]
[ИТ-сотрудник с Reddit автоматизировал свою работу и получает зарплату ни за что
](https://habr.com/ru/company/gms/blog/645541/)

**Comment by RinatValiullov** [comment]
[Web3 и NFT: хайп обоснован или нет? Ещё неясно](https://habr.com/ru/post/645807)

**Comment by RinatValiullov** [comment]
npm опять штормит

[Нарушение обратной совместимости в популярном NPM-пакете привело к сбоям в различных проектах](https://www.opennet.ru/opennews/art.shtml?num=56517)

Реактоводам. Как пофиксить

[npm dependency is breaking some React apps today — here's the fix](https://www.bleepingcomputer.com/news/security/npm-dependency-is-breaking-some-react-apps-today-heres-the-fix)

**Comment by akaguny** [comment]
Google эксперименты
https://artsandculture.google.com/experiment/blob-opera/AAHWrq360NcGbw?hl=en&cp=eyJyIjoiZXp4SHFiaU5SZkZNIn0.

**Comment by akaguny** [comment]
Сооснователь Reddit Аарон Шварц совершил самоубийство / Хабр
habr.com › ru › post › 165541
https://habr.com/ru/post/165541/
+ Крах faker.js

**Comment by AlexMzuev** [comment]
[ФСБ сообщило, что члены хак-группы REvil арестованы по запросу США](https://xakep.ru/2022/01/14/revil-fsb/)

**Comment by AlexMzuev** [comment]
[Хакеры атаковали правительственные сайты Украины](https://highload.today/bojtes-i-zhdite-hudshego-hakery-atakovali-pravitelstvennye-sajty-ukrainy-chto-govoryat-v-mintsifry/)

[Microsoft обнаружила вайпера, атакующего украинских пользователей](https://xakep.ru/2022/01/17/whispergate/)

**Comment by RinatValiullov** [comment]
> Как долго ещё это может зваться "ранними днями"? Как долго нам придётся ждать, пока кто-нибудь придумает реальное применение блокчейна, которое не будет выглядеть откровенной попыткой задним числом оправдать технологию, неэффективную во всех смыслах этого слова? Какой экологический ущерб атмосфере должен быть оправдан, пока мы ждём выхода proof-of-work блокчейнов из этапа "ранние дни"? Сколько людей должно быть обмануто и ограблено, пока блокчейн-специалисты говорят о том, что только начинают думать о создании защитных механизмов в своих платформах? Как долго неспециалисты и обыватели, которых так охотно втягивают в проекты на основе блокчейна под предлогом сделать их миллионерами, будут упрекать в том, что это их вина раз их обманывают, ведь они должны были сами уметь проверять смарт-контракты?

[Это уже не «ранние дни»](https://habr.com/ru/post/645893)

**Comment by RinatValiullov** [comment]
[Рейтинг ТОП 10 CMS сайтов: Какую лучше выбрать](https://habr.com/ru/post/645947)

<img src="https://user-images.githubusercontent.com/9755333/149771182-a2f1ce70-be65-4f43-a768-2c09ba3b977d.png" width="50%">

**Comment by RinatValiullov** [comment]
[Walmart задумался о создании собственной криптовалюты и NFT](https://habr.com/ru/news/t/646059)

`+`

[В Китае будут создавать собственный NFT-рынок при поддержке государства](https://habr.com/ru/news/t/646021)


https://user-images.githubusercontent.com/9755333/149841213-e3883162-0df2-4ba2-8a23-42784fe21b3d.mp4

**Comment by anton-okolelov** [comment]
Bolt перешел на 4х-дневку
https://www.businessinsider.com/ecommerce-unicorn-bolt-adopts-4-day-week-after-productivity-improved-2022-1

**Comment by RinatValiullov** [comment]
> ...уход обусловлен желанием проводить больше времени в семье и заниматься личными проектами

Нормальное желание нормального человека. 

[Игорь Сысоев ушёл из компаний F5 Network и покинул проект NGINX](https://www.opennet.ru/opennews/art.shtml?num=56535)

**Comment by anton-okolelov** [comment]
Обсёр собеседующих
https://highload.today/zubrit-teoriyu-eto-ne-ko-mne-ya-pishu-kod-razrabotchik-prizval-proshhe-otnositsya-k-sobesedovaniyam/

**Comment by AlexMzuev** [comment]
[Война с YouTube-dl не заканчивается](https://www.cnews.ru/news/top/2022-01-17_pravoobladateli_hotyat_unichtozhit)

**Comment by AlexMzuev** [comment]
[Егор Рогов из PostgresPro всё-таки выпустил большую книгу о том как работает Постгрес!](https://postgrespro.ru/education/books/internals)

**Comment by RinatValiullov** [comment]
[Онлайн-заседание итальянских сенаторов прервало 3D-порно по Final Fantasy](https://tjournal.ru/news/515505-onlayn-zasedanie-italyanskih-senatorov-prervalo-3d-porno-po-final-fantasy)

**Comment by RinatValiullov** [comment]
А действительно. Как так вышло? 🤔 

[Kubernetees and Microservices, how did we get from 'Simple' to 'Spaghetti'??](https://www.reddit.com/r/csharp/comments/s7d7qb/kubernetees_and_microservices_how_did_we_get_from)

**Comment by RinatValiullov** [comment]
Интересный тред про то, как один парень визуализировал движение поездов в Нидерландах.
*Ж/д сеть в Нидерландах - третья по загруженности в мире. Только Япония и Швейцария опережают её.*

[24 hours of trains in the Netherlands](https://twitter.com/yannickbrouwer/status/1483531109799534593)

**Comment by RinatValiullov** [comment]
На "потрындеть" под конец стрима

[Хабр, зачем ты сломал свою поддержку (а заодно и шапку)?](https://habr.com/ru/post/646295)

**Comment by RinatValiullov** [comment]
😸 

[HTML Is A Programming Language](https://github.com/marianoguerra/hiapl)
