### ISSUE TITLE
Темы эфира #150 (27 января) 

### ISSUE THREAD

**Issue by AlexMzuev** [znprod/stream-topics#73]
Несите свои темы, друзья!

Юбилейный выпуск, однако.

**Comment by AlexMzuev** [comment]
[«Привыкли, что ничего работоспособного в стране нет»: как в России годами пытаются «победить» Intel, Huawei и Dell](https://tjournal.ru/tech/511303-privykli-chto-nichego-rabotosposobnogo-v-strane-net-kak-v-rossii-godami-pytayutsya-pobedit-intel-huawei-i-dell)

[К нам приехал моноблок на «Байкале» для офиса — «Ну а чего вы ждали?»](https://habr.com/ru/company/croc/blog/646239/)

**Comment by AlexMzuev** [comment]
[Егор Рогов из PostgresPro всё-таки выпустил большую книгу о том как работает Постгрес!](https://postgrespro.ru/education/books/internals)

**Comment by AlexMzuev** [comment]
[Прототип отечественной ОС Phantom на базе Genode будет готов до конца года](https://www.opennet.ru/opennews/art.shtml?num=56565)

[Оригинальная статья, чуть больше подробностей](https://www.cnews.ru/news/top/2022-01-21_rossiyane_sozdali_unikalnuyu)

**Comment by AlexMzuev** [comment]
[ИТ-поставщик Минобороны добит окончательно и бесповоротно](https://www.cnews.ru/news/top/2022-01-24_problemnaya_dochka_rosteha)

**Comment by proxeter** [comment]
[Смарт-контракты в нацгвардии](https://spb.hh.ru/vacancy/51758298)

**Comment by anton-okolelov** [comment]
[Php на стероидах](https://t.me/crossjoin/143)

**Comment by dmitryplyaskin** [comment]
Нужны ли помидоры в связке сало + хлебушек + лучок?

**Comment by AlexMzuev** [comment]
[В большинстве сборок Linux нашли опасную уязвимость. Ей уже 12 лет](https://xakep.ru/2022/01/26/pwnkit/)

**Comment by AlexMzuev** [comment]
[Twist — новый язык программирования, призванный облегчить создание программ для квантовых вычислений](https://itc.ua/news/twist-novyj-yazyk-programmirovaniya-prizvannyj-oblegchit-sozdanie-programm-dlya-kvantovyh-vychislenij/)

**Comment by AlexMzuev** [comment]
[The Tor Project и Роскомсвобода обжалуют блокировку Tor в суде](https://xakep.ru/2022/01/25/tor-rks/)

**Comment by AlexMzuev** [comment]
[Хактивисты утверждают, что взломали белорусскую железную дорогу](https://xakep.ru/2022/01/25/haktivisty-utverzhdayut-chto-vzlomali-belorusskuyu-zheleznuyu-dorogu/)
