### ISSUE TITLE
Темы эфира #151 (3 февраля) - в гостях Юрий Бабак

### ISSUE THREAD

**Issue by evgwed** [znprod/stream-topics#74]
## Гость в эфире
В четверг к нам в гости придет Юрий Бабак. Расскажет нам про платежную систему Мир изнутри, про java, про кровавый энтерпрайз и многое другое.

**Набрасывайте вопросы на вентилятор в коментах тут**

## Прочие темы
Накидывайте темы, если останется время, мы их обязательно обсудим

#### Как пользователь Реддита совмещает 5 работ и зарабатывает 1,2 млн $ в год

> Перевод поста на Реддите "Я вышел на пятую работу в Понедельник".
> 
> https://vc.ru/hr/351316-kak-polzovatel-reddita-sovmeshchaet-5-rabot-i-zarabatyvaet-1-2-mln-v-god
> 
> **P.S.** Причем ему компании еще и ноуты присылают. Вот фото его рабочего места
> ![image](https://user-images.githubusercontent.com/6000708/151800679-479683e5-4339-4d69-b673-e15bf1142c5c.png)

**Comment by akaguny** [comment]
[Стратегия #NodeJS для корпоративных приложений](https://twitter.com/tshemsedinov/status/1364629059376984064)

**Comment by tym83** [comment]
Почему некоторые команды на бэке переходят с Java на Kotlin?
Кто такой джуниор с точки зрения энтерпрайза?
Все много говорят про важность софт-скилов и про то. что они перекрывают харды. А были ли случаи, когда вы брали менее скилового человека, чем обычно, за какие-то другие качества и культурный мэтч? Речь о более джуновских позициях
Какие самые большие челленджи были и сейчас стоят перед командой Мира? Какие самые большие или самые необычные фейлы происходили в разработке системы?
Как устроен процесс выкатки в прод новых фич и просто обновлений системы, на которую постоянно идет большая нагрузка и которая работает с очень чувствительными данными?
Что технически круче и защищеннее — виза или мир? Почему?
Зачем директор платежной системы Мир приходил в камеди клаб несколько лет назад и зачем Воля с Харламовым откровенно залезли своими языками в межягодичные просветы?
Что самое уроддское в Java? За что ты ее ненавидишь?

**Comment by NastyPasty12** [comment]
Гендиректор Xsolla ушёл в отставку https://tjournal.ru/525429

**Comment by anton-okolelov** [comment]
https://tjournal.ru/525441

**Comment by akaguny** [comment]
[Соискатель рассказал про стажировку в ростовской компании со штрафом за отказ от трудоустройства в 2 миллиона рублей](https://habr.com/ru/news/t/646997/)

**Comment by akaguny** [comment]
Что происходит после аварии уровня а1-а3 по вине разработки после её решения. Есть ли расследование и как оно проходит если есть? Или например как должно быть

**Comment by evgwed** [comment]
https://twitter.com/nadiiaNadi/status/1488602166420021249

Срач в твиттере, где люди ищут корреляцию внешнего вида программиста с его скиллами. Чем хуже выглядит, тем лучше кодит.

**Comment by kpblc** [comment]
Вопрос гостю
Насколько формализован процесс разработки, как часто команда уходит в анабиоз и ждет неделю согласование на выкатку релиза от заместителя замещающего заместителя эксперта безопаности?
