### ISSUE TITLE
Темы для выпуска #088  (26 ноября)

### ISSUE THREAD

**Issue by anton-okolelov** [znprod/stream-topics#8]
Не стесняйтесь, предлагайте новости, темы для обсуждения, вопросы ведущим и т.д.

**Comment by RinatValiullov** [comment]
* Как взять _технический долг_ под контроль? Как вылезти из этой __вонючей ямы нерешённых проблем и багов в продукте__? Как максимально сократить разницу между тем, что было *обещано* и тем, что в итоге было *сделано* (*доставлено*). Расскажите про внутренние процессы у вас в командах, помогающие бороться с этим неприятным и вредным явлением :smile_cat: 

![Technical-debt-featured-image2](https://user-images.githubusercontent.com/9755333/99886297-2fc5b980-2c5d-11eb-85bd-59ea0d2621dd.png)

**Comment by anton-okolelov** [comment]
Вышел php8 и
[Проблемы в современной пыхе](https://m.habr.com/ru/post/511266/)

**Comment by anton-okolelov** [comment]
Бенчмарки M1 для go standard library: https://roland.zone/m1-go-benchmarks/

**Comment by xenmayer** [comment]
[Почему AWS любит Rust](https://aws.amazon.com/ru/blogs/opensource/why-aws-loves-rust-and-how-wed-like-to-help/)

**Comment by githubjeka** [comment]
> * Как взять _технический долг_ под контроль? Как вылезти из этой **вонючей ямы нерешённых проблем и багов в продукте**? Как максимально сократить разницу между тем, что было _обещано_ и тем, что в итоге было _сделано_ (_доставлено_). Расскажите про внутренние процессы у вас в командах, помогающие бороться с этим неприятным и вредным явлением 😸

[фокус внимания на цели](https://m.habr.com/ru/post/529730/)

**Comment by anton-okolelov** [comment]
[РОИ: Обязать использовать Раст в некоторых случаях](https://www.roi.ru/71821/)

**Comment by githubjeka** [comment]
https://hey.science/dumpster-fire/

Отправляешь им email, они его распечатывают и сжигают в мусорном баке. Но сейчас у них баги, вроде как второй день исправляют ...

**Comment by xenmayer** [comment]
Видео-версия: https://youtu.be/XxdMj5E13Ss

Наш ютуб: https://www.youtube.com/channel/UC6cTShKx3lJWw-EzSr_ZAfw

Аудио-версия: https://soundcloud.com/znprod/088-pro-rust-php8-tekhdolg

Телега: https://t.me/ZnProd

Twitter: https://twitter.com/podcast_znprod

Патреон: https://www.patreon.com/ZnProd

Сайт: https://znprod.io/
