### ISSUE TITLE
Не накладывать мифические звуки на фон

### ISSUE THREAD

**Issue by xepozz** [znprod/stream-topics#9]
Придумайте какой-нибудь другой фон.
Текущий фон часто вводит в заблуждение и не только, когда вечерами гуляешь и слушаешь подкаст в наушниках. 

**Проблема:** когда никто не говорит (или звук фона выделяется поверх речи) складывается ощущение, как будто что-то где-то происходит.
**Как ролить:** погулять с подкастом в ушах темными вечерами в среднем или не очень людном месте :grin:

**Comment by zetroot** [comment]
Кстати да, пару раз приходилось делать паузу - казалось клапана застучали. Можно что то более плавное

**Comment by xenmayer** [comment]
В понедельник в ~10:30-40 в [канале](https://t.me/ZnProdChannel) и [чатике](https://t.me/ZnProd) еще раз запустим голосовалку с вопросом `стоит ли добоавлять фоновую музыку` и музыка в следующем выпуске будет по результатам)

**Comment by xepozz** [comment]
Музыка пусть будет, только жанр нужно сменить.

**Comment by makoven** [comment]
Я думал это подкастеры шуршат. А это музыка оказывается

**Comment by xenmayer** [comment]
Пока по результатам голосования музыку оставляем
![image](https://user-images.githubusercontent.com/3073695/100723107-6eccdb00-33d2-11eb-81fc-8632602cee9b.png)

Поищем новый трек на фон.

**Comment by xenmayer** [comment]
Пока больше претензий не было, закрою ишью.
В бэке поменяли музыку и сделали потише.
